# Generated by Django 6.0.7 on 2026-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_gmailinboxtoken_gmailthreadstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_body', models.TextField(blank=True)),
                ('parsed', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
