# Generated by Django 6.0.7 on 2026-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_quowebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('from_number', models.CharField(blank=True, max_length=30)),
                ('to_number', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField(blank=True)),
                ('quo_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['quo_created_at'],
            },
        ),
    ]
