# Generated by Django 6.0.7 on 2026-07-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_quomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailinboxtoken',
            name='is_send_from',
            field=models.BooleanField(default=False, help_text='Outgoing follow-up email sends through this mailbox. Only one at a time.'),
        ),
        migrations.AddField(
            model_name='gmailthreadstate',
            name='mailbox_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='gmailthreadstate',
            name='thread_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='gmailthreadstate',
            unique_together={('mailbox_email', 'thread_id')},
        ),
    ]
