# Generated by Django 6.0.8 on 2026-09-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_multi_gmail_mailbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailThreadState',
        ),
        migrations.DeleteModel(
            name='PollCursor',
        ),
    ]
