# Generated by Django 6.0.7 on 2026-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_general',
            field=models.BooleanField(default=False, help_text='A placeholder for \'not a specific property\' at this scope (e.g. "Associations (general)") — not a real unit or building. Lets a ticket be scoped to a business line without forcing a specific address when one isn\'t known.'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('general', 'General'), ('association', 'Associations'), ('str', 'Short-Term Rentals'), ('ltr', 'Long-Term Rentals'), ('commercial', 'Commercial')], default='general', max_length=20),
        ),
    ]
