# Generated by Django 6.0.7 on 2026-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_googlecalendartoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('general', 'General'), ('association', 'Associations'), ('str', 'Short-Term Rentals'), ('ltr', 'Long-Term Rentals'), ('snowbird', 'Snowbird Oversight'), ('commercial', 'Commercial')], default='general', max_length=20),
        ),
    ]
