# Generated by Django 6.0.7 on 2026-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propertyattribute_propertyattributeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='Only needed once a property type has enough properties that the New Ticket bubble picker groups them by city — safe to leave blank until then.', max_length=100),
        ),
    ]
