# Generated by Django 6.0.7 on 2026-07-23 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('quo', 'Quo'), ('gmail', 'Gmail')], default='manual', help_text='Where this contact came from — set automatically, kept for provenance/audit.', max_length=20),
        ),
        migrations.CreateModel(
            name='ContactImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('quo', 'Quo'), ('gmail', 'Gmail')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('trade', models.CharField(blank=True, max_length=100)),
                ('suggested_contact_type', models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff-adjacent'), ('other', 'Other')], default='other', max_length=20)),
                ('raw_context', models.TextField(blank=True, help_text='Evidence for the reviewer — e.g. the Quo company field or a Gmail subject line.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_contact', models.ForeignKey(blank=True, help_text='Set once approved — the real Contact this candidate became.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
