# Generated by Django 6.0.7 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact_source_contactimportcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_verified',
            field=models.BooleanField(default=False, help_text='Set automatically when USPS confirms this address on save — see core/usps.py.'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='Also used by the New Ticket bubble picker to group properties by city once a type has more than 50 of them.', max_length=100),
        ),
    ]
