# Generated by Django 6.0.7 on 2026-07-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_property_address_verified_property_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='properties',
            field=models.ManyToManyField(blank=True, help_text='The propert(y/ies) this contact is associated with — e.g. a tenant, an owner, or a board member who may sit on more than one board.', related_name='contacts', to='core.property'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('owner', 'Owner'), ('board_member', 'Board Member'), ('association_member', 'Association Member'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff-adjacent'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_legacy', to='core.property'),
        ),
        migrations.AlterField(
            model_name='contactimportcandidate',
            name='suggested_contact_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('owner', 'Owner'), ('board_member', 'Board Member'), ('association_member', 'Association Member'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff-adjacent'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
