# Generated by Django 6.0.7 on 2026-07-23 18:33

from django.db import migrations


def copy_property_to_properties(apps, schema_editor):
    Contact = apps.get_model('core', 'Contact')
    for contact in Contact.objects.filter(property__isnull=False):
        contact.properties.add(contact.property_id)


def copy_properties_to_property(apps, schema_editor):
    """Reverse: best-effort — just takes the first linked property, if any."""
    Contact = apps.get_model('core', 'Contact')
    for contact in Contact.objects.all():
        first = contact.properties.first()
        if first:
            contact.property_id = first.pk
            contact.save(update_fields=['property'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_properties_alter_contact_contact_type_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_property_to_properties, copy_properties_to_property),
    ]
