# Generated by Django 6.0.7 on 2026-07-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_copy_contact_property_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='property',
        ),
    ]
