# Generated by Django 6.0.7 on 2026-07-23 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_contact_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$', 'Enter phone as XXX-XXX-XXXX.')]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$', 'Enter phone as XXX-XXX-XXXX.')]),
        ),
    ]
