# Generated by Django 6.0.7 on 2026-07-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contact_phone_alter_staffprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='access_notes',
            field=models.TextField(blank=True, help_text='Anything else staff need to get in or navigate the property.'),
        ),
        migrations.AddField(
            model_name='property',
            name='alarm_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='gate_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='lockbox_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_network',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('owner', 'Owner'), ('board_member', 'Board Member'), ('association_member', 'Association Member'), ('on_site_staff', 'On-site Staff'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff-adjacent'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactimportcandidate',
            name='suggested_contact_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('owner', 'Owner'), ('board_member', 'Board Member'), ('association_member', 'Association Member'), ('on_site_staff', 'On-site Staff'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff-adjacent'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertySystemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(help_text='e.g. "Water shutoff", "Electrical panel", "Sprinkler timer"', max_length=120)),
                ('location', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_locations', to='core.property')),
            ],
            options={
                'ordering': ['system_name'],
            },
        ),
    ]
