# Generated by Django 6.0.7 on 2026-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_property_access_info_and_system_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendartoken',
            name='enabled_calendar_ids',
            field=models.JSONField(blank=True, default=list, help_text='Which of this Google account\'s calendars to pull onto the dashboard — empty means "just the primary calendar" (the default before anyone has touched the picker).'),
        ),
    ]
