# Generated by Django 6.0.7 on 2026-07-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_googlecalendartoken_enabled_calendar_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactimportcandidate',
            name='suggested_property',
            field=models.ForeignKey(blank=True, help_text="Best-guess property from AI classification of this contact's Quo message history (see intake/contact_classifier.py) — pre-fills the review queue's property picker, staff still confirms or changes it on approval.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.property'),
        ),
    ]
