# Generated by Django 6.0.7 on 2026-07-25 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contactimportcandidate_suggested_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quo_external_id',
            field=models.CharField(blank=True, db_index=True, help_text="This contact's stable id in Quo's own Contacts API — lets sync_quo_contacts match this row on future runs even if name/phone/email later change in Quo, and detect when Quo's own record has been edited since (see quo_updated_at).", max_length=64),
        ),
        migrations.AddField(
            model_name='contact',
            name='quo_updated_at',
            field=models.DateTimeField(blank=True, help_text="Quo's own updatedAt for this contact as of the last sync — a newer value on the next sync means something changed there, which stages a ContactUpdateCandidate for review rather than silently overwriting this row.", null=True),
        ),
        migrations.AddField(
            model_name='contactimportcandidate',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='The source system\'s own stable id for this contact (Quo\'s contact id, currently) — lets sync_quo_contacts recognize "already staged, still pending" without relying on phone/email, which can change.', max_length=64),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('quo', 'Quo'), ('gmail', 'Gmail'), ('yardi', 'Yardi')], default='manual', help_text='Where this contact came from — set automatically, kept for provenance/audit.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactimportcandidate',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('quo', 'Quo'), ('gmail', 'Gmail'), ('yardi', 'Yardi')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContactUpdateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(blank=True, max_length=200)),
                ('proposed_phone', models.CharField(blank=True, max_length=30)),
                ('proposed_email', models.EmailField(blank=True, max_length=254)),
                ('raw_context', models.TextField(blank=True, help_text='What changed in Quo, for the reviewer.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='core.contact')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('contact_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.contact')),
                ('contact_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.contact')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contact_a', 'contact_b')},
            },
        ),
    ]
