# Generated by Django 6.0.7 on 2026-07-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact_quo_external_id_contact_quo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'Eastern'), ('America/Chicago', 'Central'), ('America/Denver', 'Mountain'), ('America/Phoenix', 'Arizona (no DST)'), ('America/Los_Angeles', 'Pacific'), ('America/Anchorage', 'Alaska'), ('Pacific/Honolulu', 'Hawaii')], default='America/New_York', help_text='Overrides settings.TIME_ZONE for everything this user sees — see core.middleware.TimezoneMiddleware.', max_length=40),
        ),
    ]
