# Generated by Django 6.0.7 on 2026-07-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('quo', 'Quo'), ('gmail', 'Gmail'), ('yardi', 'Yardi'), ('document', 'Document import')], default='manual', help_text='Where this contact came from — set automatically, kept for provenance/audit.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactimportcandidate',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('quo', 'Quo'), ('gmail', 'Gmail'), ('yardi', 'Yardi'), ('document', 'Document import')], max_length=20),
        ),
    ]
