# Generated by Django 6.0.7 on 2026-07-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_contact_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='secondary_types',
            field=models.JSONField(blank=True, default=list, help_text='Additional simultaneous types beyond the primary Type above — e.g. an Owner who is also a Board Member. Never used for Vendor/Contractor, which stays single-type since it forces a Trade below. A plain list of ContactType values, not a relation — this is tag-like metadata, not something ever queried/filtered on at scale.'),
        ),
    ]
