# Generated by Django 6.0.7 on 2026-07-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contact_secondary_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('owner', 'Owner'), ('board_member', 'Board Member'), ('association_member', 'Association Member'), ('on_site_staff', 'On-site Staff'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactimportcandidate',
            name='suggested_contact_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('tenant', 'Tenant'), ('owner', 'Owner'), ('board_member', 'Board Member'), ('association_member', 'Association Member'), ('on_site_staff', 'On-site Staff'), ('vendor', 'Vendor / Contractor'), ('staff_adjacent', 'Staff'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
