# Generated by Django 6.0.7 on 2026-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_lead_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='door_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
