# Generated by Django 6.0.7 on 2026-07-26 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contactdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Sees the company-wide owner dashboard instead of the standard department dashboard. Orthogonal to role (a department/queue concept) and to User.is_superuser (Django-admin/Admin Tools access) — this is its own narrower permission.'),
        ),
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(help_text='The QuickBooks company ID this token authorizes access to.', max_length=50)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField()),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('ytd_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ytd_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ytd_net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
