# Generated by Django 6.0.7 on 2026-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_staffprofile_is_company_admin_quickbookstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_check_in_time',
            field=models.TimeField(blank=True, help_text="Used by the onsite module to compute a turnover deadline when a booking import only carries a date (the common case for ICS feeds), and to fill in a guest's check-in time on the calendar. Short-term rentals only.", null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='default_check_out_time',
            field=models.TimeField(blank=True, help_text='Same as check-in, for the checkout side of a turnover.', null=True),
        ),
    ]
