# Generated by Django 6.0.7 on 2026-08-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_property_default_checkin_checkout_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airbnb_listing_name',
            field=models.CharField(blank=True, help_text="This property's exact listing name/title on Airbnb — used by the onsite module's portfolio-wide booking import to automatically tie each reservation row to the right property. Set automatically the first time an unrecognized listing name is resolved during an import, or editable here directly.", max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='vrbo_listing_name',
            field=models.CharField(blank=True, help_text='Same as airbnb_listing_name, for VRBO.', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('airbnb_listing_name', ''), _negated=True), fields=('airbnb_listing_name',), name='uniq_property_airbnb_listing_name'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('vrbo_listing_name', ''), _negated=True), fields=('vrbo_listing_name',), name='uniq_property_vrbo_listing_name'),
        ),
    ]
