# Generated by Django 6.0.7 on 2026-08-04 18:30

import django.db.models.deletion
from django.db import migrations, models


def _copy_forward(apps, schema_editor):
    Property = apps.get_model('core', 'Property')
    PropertyListingName = apps.get_model('core', 'PropertyListingName')
    for prop in Property.objects.exclude(airbnb_listing_name='').exclude(airbnb_listing_name__isnull=True):
        PropertyListingName.objects.get_or_create(property=prop, platform='airbnb', name=prop.airbnb_listing_name)
    for prop in Property.objects.exclude(vrbo_listing_name='').exclude(vrbo_listing_name__isnull=True):
        PropertyListingName.objects.get_or_create(property=prop, platform='vrbo', name=prop.vrbo_listing_name)


def _copy_backward(apps, schema_editor):
    Property = apps.get_model('core', 'Property')
    PropertyListingName = apps.get_model('core', 'PropertyListingName')
    for row in PropertyListingName.objects.filter(platform='airbnb').order_by('created_at'):
        Property.objects.filter(pk=row.property_id, airbnb_listing_name='').update(airbnb_listing_name=row.name)
    for row in PropertyListingName.objects.filter(platform='vrbo').order_by('created_at'):
        Property.objects.filter(pk=row.property_id, vrbo_listing_name='').update(vrbo_listing_name=row.name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_property_booking_platform_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='property',
            name='uniq_property_airbnb_listing_name',
        ),
        migrations.RemoveConstraint(
            model_name='property',
            name='uniq_property_vrbo_listing_name',
        ),
        migrations.AddField(
            model_name='propertylistingname',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_names', to='core.property'),
        ),
        migrations.RunPython(_copy_forward, _copy_backward),
        migrations.RemoveField(
            model_name='property',
            name='airbnb_listing_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='vrbo_listing_name',
        ),
        migrations.AddConstraint(
            model_name='propertylistingname',
            constraint=models.UniqueConstraint(fields=('platform', 'name'), name='uniq_listing_name_per_platform'),
        ),
    ]
