# Generated by Django 6.0.7 on 2026-08-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_propertylistingname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Full admin: the company-wide owner dashboard, checklist/property editing, staff creation, and Admin Tools (including API keys/secrets) — equivalent to User.is_superuser. Orthogonal to role, which is just a department/queue concept.'),
        ),
    ]
