# Generated by Django 6.0.7 on 2026-08-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistingname',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Which unit under the property this specific listing is for — the real fix for the "3 units, 1 property record" gap this model\'s own docstring above used to flag. Blank for a single-unit property, where the listing name resolves to the whole property as it always has.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_names', to='core.unit'),
        ),
    ]
