# Generated by Django 6.0.7 on 2026-08-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_propertylistingname_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='units',
            field=models.ManyToManyField(blank=True, help_text="Specific unit(s) this contact owns/occupies, if the property has units and it's known — e.g. which condo an Owner actually owns. Independent of `properties` above, not a replacement for it: a Board Member is tied to the whole association via `properties` with no unit needed, while an individual unit Owner has both.", related_name='contacts', to='core.unit'),
        ),
    ]
