# Generated by Django 6.0.7 on 2026-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contact_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='access_code',
            field=models.CharField(blank=True, help_text='This unit\'s own door/lock code — separate from the property\'s gate/door/lockbox codes (those cover the whole building). Shown to a cleaner on the on-site visit link only once they tap "Get Code," which also marks the visit started.', max_length=50),
        ),
    ]
