# Generated by Django 6.0.7 on 2026-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_unit_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_portfolio_owner',
            field=models.BooleanField(default=False, help_text='Gates the private /portfolio/ multi-business dashboard (see the portfolio app) — deliberately a separate flag from is_company_admin, which is about the shared real-estate business and may be held by more than one person; this one is not meant to be. Not linked from the shared site nav.'),
        ),
    ]
