# Generated by Django 6.0.7 on 2026-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_staffprofile_is_portfolio_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What we pay ourselves for a standard internal-cleaner turnover here — not what the owner is billed. Used by the Cleaner Payroll report. Blank means unpriced; primarily relevant to Short-Term Rentals but not restricted to them. A specific Unit's own cleaning_fee overrides this when set.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deep_clean_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Same as cleaning_fee, but for a turnover flagged Visit.is_deep_clean. Blank falls back to cleaning_fee, same as a standard turnover.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the property\'s own cleaning_fee for this specific unit (e.g. a studio vs. a 3-bedroom under the same building) — blank means "use the property\'s price."', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='deep_clean_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Same override, for a deep-clean turnover — blank means "use the property\'s deep_clean_fee (or its cleaning_fee, if that\'s blank too)."', max_digits=8, null=True),
        ),
    ]
