# Generated by Django 6.0.7 on 2026-08-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_property_cleaning_fee_property_deep_clean_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deep_clean_fee',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='deep_clean_fee',
        ),
        migrations.AlterField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What we pay ourselves for a standard internal-cleaner turnover here — not what the owner is billed. Used by the Cleaning Payments screen. Blank means unpriced; primarily relevant to Short-Term Rentals but not restricted to them. A specific Unit's own cleaning_fee overrides this when set. A deep-clean turnover's pay is a percentage of this, controlled centrally — see onsite.CleaningPricingSettings — not a separate per-property field.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the property\'s own cleaning_fee for this specific unit (e.g. a studio vs. a 3-bedroom under the same building) — blank means "use the property\'s price." A deep clean is a percentage of whichever of these applies, set centrally — see onsite.CleaningPricingSettings.', max_digits=8, null=True),
        ),
    ]
