# Generated by Django 6.0.7 on 2026-08-20 12:53

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_property_deep_clean_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdocument',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='contact_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='property_documents/%Y/%m/'),
        ),
    ]
