# Generated by Django 6.0.7 on 2026-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_contactdocument_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cleaning_fee',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='cleaning_fee',
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom_count',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Supports a half bath, e.g. 2.5.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bed_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='turnover_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="A negotiated flat price for a standard Turnover Clean at this property, replacing the checklist-computed time x rate estimate for that one visit type specifically (deep clean and other visit types are unaffected and still price from their own checklist time). The estimate itself is still computed and shown even when this is set — useful for checking whether the negotiated price still roughly matches how long the job actually takes. Admin-only: never shown to regular staff. A specific Unit's own value overrides this when set.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bathroom_count',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bed_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedroom_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='turnover_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the property's own turnover_price_override for this specific unit. Admin-only: never shown to regular staff.", max_digits=8, null=True),
        ),
    ]
