# Generated by Django 6.0.8 on 2026-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_encrypt_quickbooks_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookstoken',
            name='last_sync_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbookstoken',
            name='last_sync_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
