# Generated by Django 6.0.8 on 2026-09-21 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_retire_generic_admin_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this key is for, e.g. "Guest message bot".', max_length=120)),
                ('key_prefix', models.CharField(help_text='The first few characters, to recognise it in the list.', max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('allow_access_info', models.BooleanField(default=False, help_text='May read gate/door/lockbox/alarm codes, the wifi password and access notes.')),
                ('allow_internal_info', models.BooleanField(default=False, help_text='May read internal notes, contacts (names, phones, emails) and document names.')),
                ('allow_faq_write', models.BooleanField(default=True, help_text='May add and correct FAQ entries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('question_key', models.CharField(db_index=True, help_text='The question, normalised, for spotting duplicates.', max_length=320)),
                ('answer', models.TextField()),
                ('origin', models.CharField(choices=[('bot', 'Written by the assistant'), ('staff', 'Written by staff')], default='bot', max_length=10)),
                ('basis', models.CharField(choices=[('host_reply', 'A reply the host sent'), ('property_record', 'From the property record'), ('inferred', 'Inferred by the assistant'), ('staff', 'Entered by staff')], default='inferred', max_length=20)),
                ('source_note', models.CharField(blank=True, help_text="Where the assistant learned it (never a guest's private details).", max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('reviewed', models.BooleanField(default=False, help_text='A person has checked this; the assistant can no longer overwrite it.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.botaccesskey')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Blank = applies to the whole property; set for an answer that is only true of one unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.unit')),
            ],
            options={
                'verbose_name': 'property FAQ entry',
                'verbose_name_plural': 'property FAQ entries',
                'ordering': ['question'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active'), ('unit__isnull', True)), fields=('property', 'question_key'), name='uniq_active_faq_property'), models.UniqueConstraint(condition=models.Q(('status', 'active'), ('unit__isnull', False)), fields=('property', 'unit', 'question_key'), name='uniq_active_faq_unit')],
            },
        ),
    ]
