# Generated by Django 6.0.8 on 2026-09-21 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_bot_access_and_property_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('fully_qualified_name', models.CharField(help_text='The account with its parents, e.g. "Trust Accounts:324 Harmon".', max_length=500)),
                ('account_type', models.CharField(blank=True, max_length=60)),
                ('account_sub_type', models.CharField(blank=True, max_length=80)),
                ('classification', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fully_qualified_name'],
            },
        ),
        migrations.AddField(
            model_name='quickbookstoken',
            name='accounts_sync_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quickbookstoken',
            name='accounts_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the chart of accounts was last read.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='qb_expense_account',
            field=models.ForeignKey(blank=True, help_text="This rental's reimbursable-expense account on the income statement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_for_properties', to='core.quickbooksaccount'),
        ),
        migrations.AddField(
            model_name='property',
            name='qb_trust_account',
            field=models.ForeignKey(blank=True, help_text="This rental's owner trust account on the balance sheet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_for_properties', to='core.quickbooksaccount'),
        ),
    ]
