# Generated by Django 6.0.8 on 2026-09-21 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_quickbooks_accounts_and_property_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_start', models.DateField(blank=True, help_text='The first month to manage; earlier transactions are ignored.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='ledger_synced_at',
            field=models.DateTimeField(blank=True, help_text="When this rental's QuickBooks transactions were last pulled in (a month can only be closed on a recent sync).", null=True),
        ),
        migrations.AddField(
            model_name='quickbookstoken',
            name='ledger_sync_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quickbookstoken',
            name='ledger_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the property transactions were last pulled in.', null=True),
        ),
        migrations.CreateModel(
            name='ClosedMonthChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('role', models.CharField(max_length=10)),
                ('txn_type', models.CharField(max_length=60)),
                ('txn_id', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('new', 'Added in QuickBooks'), ('changed', 'Changed in QuickBooks'), ('removed', 'Removed from QuickBooks')], max_length=10)),
                ('detail', models.CharField(blank=True, max_length=400)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_month_changes', to='core.property')),
            ],
            options={
                'ordering': ['-detected_at'],
                'constraints': [models.UniqueConstraint(fields=('property', 'role', 'txn_type', 'txn_id', 'kind'), name='uniq_closed_month_change')],
            },
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('expense', 'Reimbursable-expense account'), ('trust', 'Owner trust account')], max_length=10)),
                ('txn_type', models.CharField(max_length=60)),
                ('txn_id', models.CharField(max_length=40)),
                ('txn_date', models.DateField()),
                ('month', models.DateField(db_index=True, help_text='The first day of the month the transaction falls in.')),
                ('doc_num', models.CharField(blank=True, max_length=60)),
                ('payee', models.CharField(blank=True, max_length=300)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('split', models.CharField(blank=True, help_text='The other account(s) of the transaction, as QuickBooks shows them.', max_length=300)),
                ('flow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fingerprint', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(choices=[('expense', 'Expense'), ('deposit', 'Owner deposit'), ('owner_payment', 'Owner payment'), ('reimbursement', 'Expense reimbursement'), ('commission', 'Commission')], default='expense', max_length=20)),
                ('category_source', models.CharField(choices=[('default', 'Default'), ('suggested', 'Suggested'), ('user', 'Coded by a person')], default='default', max_length=10)),
                ('reviewed', models.BooleanField(default=False, help_text='A person has looked at this line and accepted its category.')),
                ('coded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Gone from QuickBooks')], default='active', max_length=10)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_in_qb', models.BooleanField(default=False, help_text='QuickBooks changed the amount, date or account after this was pulled in; a person should glance at it.')),
                ('change_note', models.CharField(blank=True, max_length=300)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Set when the month is closed; a locked line never changes.', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickbooksaccount')),
                ('coded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_lines', to='core.property')),
            ],
            options={
                'ordering': ['txn_date', 'txn_type', 'txn_id'],
                'indexes': [models.Index(fields=['property', 'month'], name='core_ledger_propert_0ed973_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'role', 'txn_type', 'txn_id'), name='uniq_ledger_line')],
            },
        ),
        migrations.CreateModel(
            name='MonthClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month.')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('totals', models.JSONField(default=dict, help_text='The figures as closed, frozen.')),
                ('warnings_acknowledged', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_closes', to='core.property')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('property', 'month'), name='uniq_month_close')],
            },
        ),
    ]
