# Generated by Django 6.0.8 on 2026-09-21 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_month_end_close_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('kind', models.CharField(help_text='"deposit" (in the bank, no platform payout) or "payout" (a platform payout not in the bank).', max_length=10)),
                ('key', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(max_length=300)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['accepted_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='closedmonthchange',
            name='uniq_closed_month_change',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerline',
            name='uniq_ledger_line',
        ),
        migrations.RemoveConstraint(
            model_name='monthclose',
            name='uniq_month_close',
        ),
        migrations.AddField(
            model_name='closedmonthchange',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_month_changes', to='core.unit'),
        ),
        migrations.AddField(
            model_name='ledgerline',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Set when the property keeps unit-level books: the unit whose accounts this line belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='core.unit'),
        ),
        migrations.AddField(
            model_name='monthclose',
            name='level',
            field=models.CharField(choices=[('property', 'One set of books for the whole property'), ('unit', 'Separate books for each unit')], default='property', help_text='The shape the month was closed in: one set of books for the property, or one per unit.', max_length=10),
        ),
        migrations.AddField(
            model_name='monthclose',
            name='recon',
            field=models.JSONField(blank=True, default=dict, help_text='The income reconciliation as closed, frozen.'),
        ),
        migrations.AddField(
            model_name='monthclose',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='month_closes', to='core.unit'),
        ),
        migrations.AddField(
            model_name='property',
            name='financials_level',
            field=models.CharField(choices=[('property', 'One set of books for the whole property'), ('unit', 'Separate books for each unit')], default='property', help_text='Whether this rental is closed as one set of books (the two accounts above) or unit by unit (each unit has its own two accounts and its own owner payment, and the property is their sum). A month already closed keeps the shape it was closed in; open months follow this setting.', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='ledger_synced_at',
            field=models.DateTimeField(blank=True, help_text="When this unit's QuickBooks transactions were last pulled in.", null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='qb_expense_account',
            field=models.ForeignKey(blank=True, help_text="This unit's reimbursable-expense account on the income statement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_for_units', to='core.quickbooksaccount'),
        ),
        migrations.AddField(
            model_name='unit',
            name='qb_trust_account',
            field=models.ForeignKey(blank=True, help_text="This unit's owner trust account on the balance sheet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_for_units', to='core.quickbooksaccount'),
        ),
        migrations.AlterField(
            model_name='ledgerline',
            name='category',
            field=models.CharField(choices=[('expense', 'Expense'), ('deposit', 'Income deposit (booking payout)'), ('owner_payment', 'Owner payment'), ('reimbursement', 'Expense reimbursement'), ('commission', 'Commission')], default='expense', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='closedmonthchange',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'role', 'txn_type', 'txn_id', 'kind'), name='uniq_closed_month_change'),
        ),
        migrations.AddConstraint(
            model_name='closedmonthchange',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'role', 'txn_type', 'txn_id', 'kind'), name='uniq_closed_month_change_unit'),
        ),
        migrations.AddConstraint(
            model_name='ledgerline',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'role', 'txn_type', 'txn_id'), name='uniq_ledger_line'),
        ),
        migrations.AddConstraint(
            model_name='ledgerline',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'role', 'txn_type', 'txn_id'), name='uniq_ledger_line_unit'),
        ),
        migrations.AddConstraint(
            model_name='monthclose',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'month'), name='uniq_month_close'),
        ),
        migrations.AddConstraint(
            model_name='monthclose',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'month'), name='uniq_month_close_unit'),
        ),
        migrations.AddField(
            model_name='reconacceptance',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconacceptance',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_acceptances', to='core.property'),
        ),
        migrations.AddField(
            model_name='reconacceptance',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recon_acceptances', to='core.unit'),
        ),
        migrations.AddIndex(
            model_name='reconacceptance',
            index=models.Index(fields=['property', 'month'], name='core_recona_propert_06ea7b_idx'),
        ),
    ]
