# Generated by Django 6.0.8 on 2026-09-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_unit_level_books_and_income_recon'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='access_notes',
            field=models.TextField(blank=True, help_text="How to get into this unit (which door, which side of the building) — private, like the property's access notes."),
        ),
        migrations.AddField(
            model_name='unit',
            name='wifi_network',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
