# Generated by Django 6.0.8 on 2026-09-21 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_unit_wifi_and_access_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysystemlocation',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Set when this is inside one unit (its own shutoff or panel); blank for something that serves the whole building.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_locations', to='core.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='alarm_code',
            field=models.CharField(blank=True, help_text="This unit's own alarm code, when it has one (else the building's applies).", max_length=50),
        ),
        migrations.AddField(
            model_name='unit',
            name='lockbox_code',
            field=models.CharField(blank=True, help_text="This unit's own lockbox code, when it has one (else the building's applies).", max_length=50),
        ),
        migrations.CreateModel(
            name='ListingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_source', models.CharField(blank=True, choices=[('auto', 'Read from the listing'), ('manual', 'Entered by hand')], max_length=10)),
                ('rating_checked_at', models.DateTimeField(blank=True, help_text='When the rating was last successfully read or entered.', null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('check_error', models.CharField(blank=True, help_text='Why the last automatic read did not work, if it did not.', max_length=200)),
                ('failures', models.PositiveSmallIntegerField(default=0, help_text='Automatic reads in a row that did not work.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='core.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='core.unit')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='ListingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('auto', 'Read from the listing'), ('manual', 'Entered by hand')], default='auto', max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.listinglink')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='TrashSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trash_schedule', to='core.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrashRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trash', 'Regular trash'), ('bulk', 'Bulk pickup'), ('recycling', 'Recycling'), ('custom', 'Custom')], max_length=12)),
                ('label', models.CharField(blank=True, help_text='The name of a custom pickup (vegetation, yard waste, ...); blank for the standard kinds.', max_length=60)),
                ('days', models.JSONField(default=list, help_text='Weekday numbers, 0 = Monday ... 6 = Sunday.')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.trashschedule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='listinglink',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'platform'), name='uniq_listing_link'),
        ),
        migrations.AddConstraint(
            model_name='listinglink',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'platform'), name='uniq_listing_link_unit'),
        ),
        migrations.AddConstraint(
            model_name='trashrule',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'custom'), _negated=True), fields=('schedule', 'kind'), name='uniq_trash_rule_kind'),
        ),
    ]
