# Generated by Django 6.0.8 on 2026-09-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_seed_trash_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='exclude_from_stats',
            field=models.BooleanField(default=False, help_text="Leave this unit out of the rental performance statistics — an owner's unit that is rarely rented, say. It stays on the calendars; it just isn't counted in occupancy, rates, revenue or gaps."),
        ),
    ]
