# Generated by Django 6.0.8 on 2026-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_unit_exclude_from_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconacceptance',
            name='prior_period',
            field=models.BooleanField(default=False, help_text='A deposit that pays out something from before the books start (the first month could not have had it carried forward).'),
        ),
    ]
