# Generated by Django 6.0.8 on 2026-09-21 23:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_reconacceptance_prior_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Our commission, as a percent of the month's net income (income deposits less reimbursable expenses and expenses paid from trust). Only an administrator can change it.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
