# Generated by Django 6.0.8 on 2026-09-21 23:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_property_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Our commission, as a percent of the month's income deposits (the top line: we are paid whether or not the month is profitable). Only an administrator can change it.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
