# Generated by Django 6.0.8 on 2026-09-21 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_commission_rate_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('events', models.JSONField(default=list)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('tied_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recon_tie', to='core.ledgerline')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_ties', to='core.property')),
                ('tied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recon_ties', to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'month'], name='core_recont_propert_866065_idx')],
            },
        ),
    ]
