# Generated by Django 6.0.8 on 2026-09-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_recontie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerline',
            name='description',
            field=models.CharField(blank=True, help_text="Our own wording for this transaction, when QuickBooks's memo needs correcting. QuickBooks's memo stays beside it and a sync never overwrites this.", max_length=500),
        ),
    ]
