# Generated by Django 6.0.8 on 2026-09-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_ledgerline_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconacceptance',
            name='reason',
            field=models.CharField(blank=True, choices=[('timing', 'Timing — paid out or deposited in another month'), ('error', 'Bookkeeping error / something to chase'), ('prior_books', 'From before the books')], help_text='Why it is a reconciling item: a timing difference that clears itself, or a genuine bookkeeping error.', max_length=12),
        ),
        migrations.CreateModel(
            name='ReconMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('kind', models.CharField(choices=[('user', 'Matched by hand'), ('hold', 'Kept open')], default='user', max_length=6)),
                ('lines', models.JSONField(default=list)),
                ('events', models.JSONField(default=list)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_matches', to='core.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recon_matches', to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'month'], name='core_reconm_propert_bd953d_idx')],
            },
        ),
    ]
