# Generated by Django 6.0.8 on 2026-09-24 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_copy_recontie_to_reconmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReopenedClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=10)),
                ('month', models.DateField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('totals', models.JSONField(default=dict)),
                ('recon', models.JSONField(blank=True, default=dict)),
                ('warnings_acknowledged', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('reopened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopened_closes', to='core.property')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.unit')),
            ],
            options={
                'ordering': ['-reopened_at'],
            },
        ),
    ]
