# Generated by Django 6.0.8 on 2026-09-25 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_reopenedclose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QBRecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.PositiveIntegerField(help_text='The onsite PayoutBatch this deposit was matched to.')),
                ('source', models.CharField(max_length=20)),
                ('deposit_qb_id', models.CharField(max_length=40)),
                ('deposit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_lines', models.JSONField(default=list)),
                ('new_lines', models.JSONField(default=list)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('automatic', models.BooleanField(default=False)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('deposit_qb_id',), name='uniq_qb_recode_deposit')],
            },
        ),
    ]
