# Generated by Django 6.0.8 on 2026-09-29 14:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_qbrecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_basis',
            field=models.CharField(choices=[('gross', 'Gross income deposits'), ('net', 'Net income (deposits, less expenses and Owner Baseline Expenses)')], default='gross', help_text='Whether the commission rate above applies to gross income deposits (the usual case) or to net income.', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_baseline_expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='A real monthly cost of the property that never runs through us — e.g. insurance the owner pays directly — subtracted from income before commission is calculated on net income. Has no effect unless the commission basis above is Net; never reduces the owner payment a second time (the owner already paid it themselves). Applies to months still open; a closed month keeps the figure it was closed with.', max_digits=10),
        ),
    ]
