# Generated by Django 6.0.8 on 2026-10-05 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_commission_basis_and_baseline_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialssettings',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='The property management bank account in QuickBooks - what the month-end bank tie-out compares to the statement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickbooksaccount'),
        ),
        migrations.AddField(
            model_name='financialssettings',
            name='trust_parent_account',
            field=models.ForeignKey(blank=True, help_text='The parent of every property trust account in QuickBooks - its total should equal the bank account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickbooksaccount'),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month the statement covers.', unique=True)),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('read_balance', models.DecimalField(blank=True, decimal_places=2, help_text='What the program read from the file, kept so a correction is visible.', max_digits=14, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTieOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('run_at', models.DateTimeField(auto_now=True)),
                ('qb_bank', models.DecimalField(decimal_places=2, max_digits=14)),
                ('qb_trust', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prior_bank', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prior_trust', models.DecimalField(decimal_places=2, max_digits=14)),
                ('differences', models.JSONField(default=list)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TieOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month it belongs to (first day).')),
                ('side', models.CharField(choices=[('statement', 'Statement vs QuickBooks bank'), ('trust', 'QuickBooks bank vs trust accounts')], max_length=10)),
                ('txn_key', models.CharField(blank=True, help_text='The QuickBooks transaction (type:id) when accepted from the list; blank for one entered by hand.', max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month', 'created_at'],
            },
        ),
    ]
