# Generated by Django 6.0.8 on 2026-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_bank_tieout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='ending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blank until a person types or confirms it, when the file could not be read.', max_digits=14, null=True),
        ),
    ]
