# Generated by Django 6.0.8 on 2026-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_bank_statement_balance_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='income_collected_by_owner',
            field=models.BooleanField(default=False, help_text="The owner collects this rental's booking income themselves (the platform pays them, not our trust account) and pays us at the end of the month for our expenses and commission. Its platform payouts are never expected at our bank; commission is a percent of the month's payouts (gross only); and its statement shows no income, only our expenses and commission."),
        ),
    ]
