# Generated by Django 6.0.8 on 2026-10-06 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_income_collected_by_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first month of the books these are the opening figures for.')),
                ('owner_payable', models.DecimalField(decimal_places=2, default=0, help_text='Owed to the owner.', max_digits=12)),
                ('reimbursable', models.DecimalField(decimal_places=2, default=0, help_text='Reimbursable expenses the trust account still owed us.', max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Commission still owed to us.', max_digits=12)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='core.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='core.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'unit', 'month'), name='uniq_opening_balance')],
            },
        ),
    ]
