# Generated by Django 6.0.8 on 2026-10-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_portal_open',
            field=models.BooleanField(default=False, help_text='The owner portal is open for this rental: its owner contacts (with an email address) can sign up and see the months you release to owners, and are emailed when you release one. Off for every rental until you turn it on.'),
        ),
        migrations.CreateModel(
            name='OwnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Lower case. The address they signed up with and the contact they are matched to.', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Staff can switch an owner off here without deleting anything.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, help_text='Too many wrong passwords: no login until then.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='OwnerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Sign-up'), ('reset', 'Forgotten password')], max_length=10)),
                ('code_hash', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose'], name='core_ownerc_email_6109ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month.')),
                ('released_at', models.DateTimeField()),
                ('snapshot', models.JSONField()),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('revisions', models.JSONField(default=list, help_text='Each time a released month changed: when, and what (figure, was, now).')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_releases', to='core.property')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('property', 'month'), name='uniq_month_release')],
            },
        ),
    ]
