# Generated by Django 6.0.7 on 2026-08-04 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_property_default_checkin_checkout_times'),
        ('tickets', '0029_alter_ticket_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('color', models.CharField(blank=True, help_text='CSS color/variable for the dashboard board.', max_length=20)),
                ('default_duration_minutes', models.PositiveIntegerField(default=90)),
                ('requires_deadline', models.BooleanField(default=True, help_text="True for turnovers, which must beat the next check-in. False for deep cleans/inspections scheduled between guests, where there's no hard ready_by.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO'), ('manual', 'Manual')], max_length=20)),
                ('external_uid', models.CharField(help_text='UID from the ICS/CSV row — the idempotency key.', max_length=200)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_phone_last4', models.CharField(blank=True, max_length=4)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Updated on every import that still contains this UID — a row not touched by an import covering its date range is presumed cancelled off the guest's platform.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.property')),
            ],
            options={
                'ordering': ['check_out'],
                'unique_together': {('source', 'external_uid')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20)),
                ('raw_file', models.FileField(upload_to='onsite_import_batches/%Y/%m/')),
                ('covers_start', models.DateField(help_text='Earliest checkout date this file actually covers.')),
                ('covers_end', models.DateField(help_text='Latest checkout date this file actually covers.')),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('changed_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_import_batches', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, help_text='e.g. "Kitchen", "Bathrooms" — for grouping.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('mandatory', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_note', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_attributes', models.ManyToManyField(blank=True, help_text='This item only resolves at properties tagged with ALL of these attributes (e.g. "has_grill") — leave empty to apply everywhere.', related_name='onsite_checklist_items', to='core.propertyattribute')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_items', to='onsite.visittype')),
            ],
            options={
                'ordering': ['visit_type', 'section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_start', models.TimeField(blank=True, null=True)),
                ('ready_by', models.DateTimeField(blank=True, help_text='Defaults to next_booking.check_in when set. Null means no hard deadline.', null=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='unassigned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=200)),
                ('google_sync_pending', models.BooleanField(default=False)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='onsite_signatures/%Y/%m/')),
                ('signed_name', models.CharField(blank=True, max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff-authored, visible to the assignee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_contact', models.ForeignKey(blank=True, help_text='Use for an external/contract cleaner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_visits', to='core.contact')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_visits', to='core.staffprofile')),
                ('booking', models.ForeignKey(blank=True, help_text='The checkout that generated this visit, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='onsite.booking')),
                ('next_booking', models.ForeignKey(blank=True, help_text='The check-in this visit has to beat — drives ready_by.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_before', to='onsite.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.property')),
            ],
            options={
                'ordering': ['scheduled_date', 'ready_by'],
            },
        ),
        migrations.CreateModel(
            name='VisitChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('standard', 'Standard'), ('property', 'Property-specific'), ('oneoff', 'One-off')], max_length=20)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('mandatory', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_note', models.BooleanField(default=False)),
                ('is_new_unreviewed', models.BooleanField(default=False, help_text='Added to the standard list after this property was last reviewed.')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('skip_reason', models.CharField(blank=True, help_text='Required to pass a mandatory item without completing it.', max_length=300)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onsite.visit')),
            ],
            options={
                'ordering': ['visit', 'section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VisitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_issue', to='tickets.ticket')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='onsite.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='onsite_visit_media/%Y/%m/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='onsite.visitchecklistitem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='onsite.visit')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_months', models.PositiveIntegerField(default=3)),
                ('last_generated_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_rules', to='core.staffprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_rules', to='core.property')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='onsite.visittype')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='created_from_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_visits', to='onsite.visitrule'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='onsite.visittype'),
        ),
        migrations.CreateModel(
            name='PropertyChecklistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_checklist_reviews', to='core.property')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='onsite.visittype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChecklistOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
                ('mandatory_override', models.BooleanField(blank=True, null=True)),
                ('order_override', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_checklist_overrides', to='core.property')),
                ('standard_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='onsite.standardchecklistitem')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_overrides', to='onsite.visittype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('mandatory', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_custom_items', to='core.property')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_custom_items', to='onsite.visittype')),
            ],
            options={
                'ordering': ['property', 'visit_type', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_staff__isnull', True), ('assigned_contact__isnull', True), _connector='OR'), name='visit_single_assignee'),
        ),
        migrations.AlterUniqueTogether(
            name='propertychecklistreview',
            unique_together={('property', 'visit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='propertychecklistoverride',
            unique_together={('property', 'standard_item')},
        ),
    ]
