# Generated by Django 6.0.7 on 2026-08-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmedia',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='Set when this photo was attached to a reported issue rather than a checklist item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='onsite.visitissue'),
        ),
    ]
