# Generated by Django 6.0.7 on 2026-08-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_property_booking_platform_names'),
        ('onsite', '0002_visitmedia_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onsite_import_batches', to='core.property'),
        ),
    ]
