# Generated by Django 6.0.7 on 2026-08-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0003_alter_importbatch_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUploadSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20)),
                ('filename_hint', models.CharField(blank=True, help_text="A substring (case-insensitive) often found in this file's real filename — used only to highlight a likely match when someone browses instead of dragging; dropping a file directly onto this slot always uses it regardless of filename. Leave blank if there's no reliable pattern.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='onsite.importbatch')),
                ('last_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
