# Generated by Django 6.0.7 on 2026-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0004_dailyuploadslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFeedHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20, unique=True)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('newest_booked_date', models.DateField(blank=True, null=True)),
                ('coverage_through', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'booking feed health',
                'ordering': ['source'],
            },
        ),
    ]
