# Generated by Django 6.0.7 on 2026-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0006_clean_slate_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuploadslot',
            name='required_columns',
            field=models.CharField(blank=True, help_text='Comma-separated column names (case-insensitive, matched against the file\'s header row) that MUST be present for a dropped file to be accepted here — e.g. "Confirmation Code, Start Date, End Date, Listing". A file missing any of these is rejected outright with a clear error before anything is parsed or saved, so dropping the wrong platform\'s file into this slot can\'t silently misread columns. Leave blank to skip this check for this slot (only the importer\'s own generic required columns still apply).', max_length=500),
        ),
    ]
