# Generated by Django 6.0.7 on 2026-08-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0007_dailyuploadslot_required_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuploadslot',
            name='is_cancellations_only',
            field=models.BooleanField(default=False, help_text='Check this for a slot whose file only ever contains cancelled reservations (e.g. "Airbnb Cancellations") rather than a full listing of everything currently on the books. Copied onto each ImportBatch created from this slot — see that field\'s help text for why it matters. Leave unchecked for a normal "here\'s everything upcoming" reservations report.'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='is_cancellations_only',
            field=models.BooleanField(default=False, help_text="Copied from DailyUploadSlot.is_cancellations_only at upload time (False for the generic upload form). When True, this file is a PARTIAL listing that only contains cancelled reservations (e.g. Airbnb's separate Cancellations report) — the diff must not treat a booking simply being absent from it as evidence of cancellation, since every other still-active booking is absent from it too by design. See onsite/services/bookings.py::diff_bookings."),
        ),
    ]
