# Hand-written (not autogenerated) — makemigrations has no TTY to answer its
# "did you rename this field?" prompt in this environment, so a plain
# `makemigrations` here would produce a RemoveField+AddField pair instead
# and silently DROP the is_cancellations_only=True already set on the real
# "Airbnb Cancellations" slot. RenameField is a plain column rename at the
# DB level (no data loss) on both SQLite and Postgres.
#
# Renamed rather than just re-scoped in place because "is_cancellations_only"
# would now be a straight-up lie once also set True for the Airbnb Page 1/
# Page 2 slots (see 0011_mark_airbnb_pages_partial.py) — those slots' files
# are NOT cancellations-only, they're just one piece of a paginated list.
# is_partial_listing accurately covers both reasons a file can't be trusted
# for absence-based cancellation inference.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0009_seed_slot_format_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuploadslot',
            old_name='is_cancellations_only',
            new_name='is_partial_listing',
        ),
        migrations.RenameField(
            model_name='importbatch',
            old_name='is_cancellations_only',
            new_name='is_partial_listing',
        ),
        # RenameField only renames the column — bring the migration state's
        # help_text in line with the new wording in models.py so
        # makemigrations --check doesn't see a pending AlterField afterward.
        migrations.AlterField(
            model_name='dailyuploadslot',
            name='is_partial_listing',
            field=models.BooleanField(
                default=False,
                help_text='Check this for a slot whose file is NOT a complete, standalone listing of '
                           'everything currently on the books for this source — either it only ever '
                           'contains cancelled reservations ("Airbnb Cancellations"), or it\'s one of '
                           'several pages/pieces of a larger list (e.g. "Airbnb - Upcoming Page 1" and '
                           '"Page 2", where neither page alone contains everything — a booking that\'s '
                           "only on the other page must never look cancelled just because it's absent "
                           "from this one). Copied onto each ImportBatch created from this slot — see "
                           "that field's help text for why it matters. Leave unchecked only for a slot "
                           "whose file is, by itself, everything currently upcoming for that source (e.g. "
                           "VRBO's combined report).",
            ),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='is_partial_listing',
            field=models.BooleanField(
                default=False,
                help_text='Copied from DailyUploadSlot.is_partial_listing at upload time (False for the '
                           'generic upload form). When True, this file does NOT represent a complete, '
                           "current listing of everything active for this source — either because it "
                           "only ever contains cancelled reservations (Airbnb's separate Cancellations "
                           "report), or because it's one of several pages/pieces of the full list "
                           "(Airbnb's Page 1/Page 2 split, say). Either way, the diff must not treat a "
                           "booking simply being absent from THIS file as evidence of cancellation — "
                           "plenty of still-active bookings are legitimately absent from a partial file "
                           "too (a Page-1-only booking is absent from Page 2, and vice versa). See "
                           "onsite/services/bookings.py::diff_bookings.",
            ),
        ),
    ]
