# Generated by Django 6.0.7 on 2026-08-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0011_mark_airbnb_pages_partial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyuploadslot',
            name='is_partial_listing',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='is_partial_listing',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='reactivated_count',
            field=models.PositiveIntegerField(default=0, help_text='Reservations that came back ACTIVE after previously being marked Cancelled — see onsite/services/bookings.py::diff_bookings\'s "reactivated" bucket.'),
        ),
    ]
