# Generated by Django 6.0.7 on 2026-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0012_remove_dailyuploadslot_is_partial_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='listing_name',
            field=models.CharField(blank=True, help_text='The platform\'s own listing title for this specific reservation (from the portfolio CSV\'s listing/property column — see RawBooking.listing_name), e.g. "800 Tropic - Wave (C)". Property records a multi-unit address as ONE row (see PropertyListingName\'s docstring), so this is the only reliable way to tell which of several actual units at that address a given reservation — and its cleaning Visit — is for. Blank for a single-property .ics import, which has no listing column.', max_length=200),
        ),
    ]
