# Generated by Django 6.0.7 on 2026-08-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0013_booking_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_deep_clean',
            field=models.BooleanField(default=False, help_text="This turnover also includes the deep-clean extra checklist items — see the addon VisitType's standard_items. Only changeable before the visit starts."),
        ),
        migrations.AddField(
            model_name='visittype',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='A checklist bundle that gets added onto another visit (e.g. Deep Clean extras added onto a Turnover) rather than a kind of visit that gets scheduled on its own — excluded from visit-type pickers. Its standard_items are still managed normally through the checklist editor.'),
        ),
        migrations.AlterField(
            model_name='visitchecklistitem',
            name='source',
            field=models.CharField(choices=[('standard', 'Standard'), ('property', 'Property-specific'), ('oneoff', 'One-off'), ('deep_clean', 'Deep clean extra')], max_length=20),
        ),
    ]
