# Generated by Django 6.0.7 on 2026-08-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0015_refresh_checklist_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardchecklistitem',
            options={'ordering': ['visit_type', 'order']},
        ),
        migrations.AlterModelOptions(
            name='visitchecklistitem',
            options={'ordering': ['visit', 'order']},
        ),
    ]
