# Generated by Django 6.0.7 on 2026-08-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_propertylistingname_unit'),
        ('onsite', '0016_alter_standardchecklistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Which unit under the property this reservation is for — resolved from the matched PropertyListingName.unit at import time. Blank for a single-unit property.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.unit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Which unit under the property this visit is for, if any — carried over from the generating Booking. Checklist resolution stays property-level regardless (a shared building checklist); only the visit record itself is unit-aware.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='listing_name',
            field=models.CharField(blank=True, help_text='The platform\'s own listing title for this specific reservation (from the portfolio CSV\'s listing/property column — see RawBooking.listing_name), e.g. "800 Tropic - Wave (C)". Kept verbatim for reference/audit even now that `unit` above carries the actual resolved unit — useful when a listing name hasn\'t been pinned to a specific Unit yet. Blank for a single-property .ics import, which has no listing column.', max_length=200),
        ),
    ]
