# Generated by Django 6.0.7 on 2026-08-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contact_units'),
        ('onsite', '0017_booking_unit_visit_unit_alter_booking_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrule',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Which unit under the property this rule generates visits for. Blank means the whole property (or a single-unit property, where this always stays blank).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_rules', to='core.unit'),
        ),
    ]
