# Generated by Django 6.0.7 on 2026-08-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0018_visitrule_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What was actually paid for this specific cleaning, locked in at the moment payment_batch was set — unlike cleaner_payout_amount() (used for what's still owed), this deliberately does NOT track later edits to the property/unit's price. A real payment already made shouldn't silently reprice itself.", max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='CleaningPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, help_text='Optional — how it was paid, a check number, etc.', max_length=300)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='payment_batch',
            field=models.ForeignKey(blank=True, help_text='Set once this cleaning has actually been paid for — see the Cleaning Payments screen. Null means still owed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='onsite.cleaningpaymentbatch'),
        ),
    ]
