# Generated by Django 6.0.7 on 2026-08-19 17:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0019_visit_paid_amount_cleaningpaymentbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deep_clean_fee_percent', models.DecimalField(decimal_places=1, default=Decimal('150.0'), help_text='A deep clean pays this percent of the normal cleaning fee — 150 means 1.5x the standard rate. Applied in Visit.cleaner_payout_amount().', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
