# Generated by Django 6.0.7 on 2026-08-20 12:53

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0020_cleaningpricingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='raw_file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='onsite_import_batches/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='visitmedia',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='onsite_visit_media/%Y/%m/'),
        ),
    ]
