# Generated by Django 6.0.7 on 2026-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0021_alter_importbatch_raw_file_alter_visitmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrule',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Day-based cadence (e.g. 7 for weekly, 14 for biweekly) — takes precedence over interval_months when set. Leave blank for a month-based cadence like a quarterly deep clean/inspection. Exists because relativedelta(months=...) has no way to express anything shorter than a month, which a weekly commercial common-area clean needs.', null=True),
        ),
    ]
