# Generated by Django 6.0.7 on 2026-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0022_visitrule_interval_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningpricingsettings',
            name='deep_clean_fee_percent',
        ),
        migrations.AddField(
            model_name='cleaningpricingsettings',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dollars per hour, used to translate any visit's estimated_minutes() into a price. Blank means no rate has been set yet — a visit with no Property/Unit.turnover_price_override is unpriced until this is.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertychecklistitem',
            name='minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertychecklistitem',
            name='scales_by',
            field=models.CharField(choices=[('flat', 'Flat (once per visit)'), ('bedrooms', 'Per bedroom'), ('beds', 'Per bed'), ('bathrooms', 'Per bathroom'), ('sqft', 'Per 1,000 sq ft')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='standardchecklistitem',
            name='minutes',
            field=models.PositiveIntegerField(default=0, help_text='How long this step takes, in minutes — per occurrence when scales_by is FLAT, or per bed/bedroom/bathroom/1,000 sq ft otherwise.'),
        ),
        migrations.AddField(
            model_name='standardchecklistitem',
            name='scales_by',
            field=models.CharField(choices=[('flat', 'Flat (once per visit)'), ('bedrooms', 'Per bedroom'), ('beds', 'Per bed'), ('bathrooms', 'Per bathroom'), ('sqft', 'Per 1,000 sq ft')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='visitchecklistitem',
            name='minutes',
            field=models.PositiveIntegerField(default=0, help_text="This step's estimated minutes for THIS visit specifically — already multiplied by the property/unit's bed/bathroom/sqft count at the moment this visit was created (see onsite/services/checklist.py::create_visit), then frozen here same as everything else about a snapshotted checklist. A later edit to the property's bed count or the standard item's per-unit minutes never changes an already-created visit's estimate."),
        ),
    ]
