# Generated by Django 6.0.7 on 2026-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0023_remove_cleaningpricingsettings_deep_clean_fee_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What was actually paid for this specific cleaning, locked in at the moment payment_batch was set — unlike effective_price() (used for what's still owed), this deliberately does NOT track a later rate change or override edit. A real payment already made shouldn't silently reprice itself.", max_digits=8, null=True),
        ),
    ]
