# Generated by Django 6.0.7 on 2026-09-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0026_reseq_checklist_items_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='manual_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Set to force this ONE visit's price to an exact amount, bypassing both the property/unit turnover_price_override and the checklist-time/hourly-rate calculation entirely — see effective_price(). For the rare one-off correction (a negotiated exception, a mistake in the checklist-based estimate) that shouldn't change every other visit at this property. Admin-only. Has no effect once the visit is already paid — paid_amount is what was actually locked in; undo that payment batch first if a paid amount needs correcting.", max_digits=8, null=True),
        ),
    ]
