# Generated by Django 6.0.8 on 2026-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0030_repair_reworded_checklist_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnsiteCalendarHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('needs_reconnect', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'on-site calendar health',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='google_synced_state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
