# Generated by Django 6.0.8 on 2026-09-20 15:36

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_quickbooks_sync_status'),
        ('onsite', '0031_calendar_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_feed',
            field=models.BooleanField(default=False, help_text="Created by polling a BookingFeed (an .ics link), which can only see the calendar's own UID — not necessarily the confirmation code a later CSV report will use. Lets that CSV import recognize the same reservation (same property, same dates) and adopt its confirmation code instead of creating a duplicate booking and cleaning."),
        ),
        migrations.CreateModel(
            name='BookingFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20)),
                ('url', core.fields.EncryptedTextField(help_text='The calendar (.ics) link from the platform.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('last_summary', models.CharField(blank=True, max_length=255)),
                ('missing_streak', models.JSONField(blank=True, default=dict)),
                ('cancellations_held', models.PositiveIntegerField(default=0, help_text='Reservations that vanished from the feed all at once and were NOT auto-cancelled pending a human confirming.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_feeds', to='core.property')),
                ('unit', models.ForeignKey(blank=True, help_text='Required when the property has units — which unit this listing is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_feeds', to='core.unit')),
            ],
            options={
                'ordering': ['property__name', 'unit__label', 'source'],
            },
        ),
    ]
