# Generated by Django 6.0.8 on 2026-09-20 16:06

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0032_booking_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfeed',
            name='not_listed',
            field=models.BooleanField(default=False, help_text="Not a real feed: records that someone decided this listing is deliberately NOT on this platform, so the Booking calendars screen doesn't keep flagging it as unconnected. Has no link and is never polled."),
        ),
        migrations.AlterField(
            model_name='bookingfeed',
            name='url',
            field=core.fields.EncryptedTextField(blank=True, help_text='The calendar (.ics) link from the platform.'),
        ),
    ]
