# Generated by Django 6.0.8 on 2026-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0035_visitrule_next_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittype',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="An agreed flat charge for EVERY visit of this type — supersedes the checklist-time x hourly-rate calculation. Blank = price from the checklist as usual. A one-off manual override on a single visit, and a property's own negotiated turnover price, both still win over this. Admin only. See Visit.effective_price().", max_digits=8, null=True),
        ),
    ]
