# Generated by Django 6.0.8 on 2026-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0039_booking_amounts_and_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='google_notify_state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
