# Generated by Django 6.0.8 on 2026-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0040_visit_google_notify_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO'), ('manual', 'In-house')], max_length=20),
        ),
    ]
