# Generated by Django 6.0.8 on 2026-09-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0041_booking_source_inhouse_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
