# Generated by Django 6.0.8 on 2026-09-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0042_booking_payout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manually_cancelled',
            field=models.BooleanField(default=False, help_text='A person marked this reservation cancelled (e.g. it was a duplicate, or the platform never said so). Uploads and calendar polls leave it cancelled instead of bringing it back.'),
        ),
    ]
