# Generated by Django 6.0.8 on 2026-09-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0043_booking_manually_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_real',
            field=models.BooleanField(default=False, help_text='A person checked this reservation is genuine even though no payout has shown up for it, so it is left off the "reservations to review" list.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_status',
            field=models.CharField(blank=True, help_text='"paid" or "scheduled", from the payout report.', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingfeedhealth',
            name='payouts_through',
            field=models.DateField(blank=True, help_text='The latest payout date any uploaded payout report has shown for this platform. A future reservation with no payout is only suspicious when its payout would fall on or before this.', null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('reservations', 'Reservations'), ('payouts', 'Payouts only')], default='reservations', help_text='A payouts-only file (VRBO "upcoming payouts") has amounts but no stay dates, so it can only attach money to reservations that are already on record.', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='kind',
            field=models.CharField(choices=[('early_checkin', 'Early check-in'), ('late_checkout', 'Late checkout'), ('early_checkout', 'Early checkout'), ('late_checkin', 'Late check-in')], max_length=20),
        ),
        migrations.CreateModel(
            name='PendingPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20)),
                ('external_uid', models.CharField(max_length=100)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source', 'external_uid')},
            },
        ),
    ]
