# Generated by Django 6.0.8 on 2026-09-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0044_payouts_review_and_time_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_seen_at',
            field=models.DateTimeField(blank=True, help_text='When a calendar poll last saw this stay.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='on_calendar',
            field=models.BooleanField(default=False, help_text='The synced platform calendar shows this stay right now (same listing, same dates). The calendars are the source of truth for cleanings and the Rentals board; a reservation that only came in from a payment report is a financial record and never gets a cleaning where a calendar is connected.'),
        ),
    ]
