# Generated by Django 6.0.8 on 2026-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0046_mark_calendar_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='other_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resolution payouts and adjustments paid or taken with this reservation payout (not revenue).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pass_through_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pass-through tax paid to the host with this reservation payout (not revenue).', max_digits=10, null=True),
        ),
    ]
