# Generated by Django 6.0.8 on 2026-09-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0047_booking_pass_through_and_other_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reservation', 'Reservation payout'), ('pass_through', 'Pass-through tax'), ('other', 'Resolution or adjustment')], max_length=14)),
                ('date', models.DateField(help_text='The day the platform paid it out.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_lines', to='onsite.booking')),
            ],
            options={
                'ordering': ['date', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'kind', 'date'), name='uniq_payout_line')],
            },
        ),
    ]
