# Generated by Django 6.0.8 on 2026-09-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_ledgerline_description'),
        ('onsite', '0048_payoutline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO')], max_length=20)),
                ('date', models.DateField(help_text='The day the platform paid it out.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail', models.CharField(blank=True, help_text="The platform's own description of the transfer, e.g. which bank account it went to.", max_length=300)),
                ('reference', models.CharField(blank=True, help_text="The platform's own reference/confirmation for this transfer.", max_length=60)),
                ('arriving_by', models.DateField(blank=True, help_text='When the platform said the money would reach the bank.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_batches', to='core.property')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('source', 'date', 'amount', 'reference'), name='uniq_payout_batch')],
            },
        ),
    ]
