# Generated by Django 6.0.8 on 2026-09-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0049_payoutbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='no_checklist',
            field=models.BooleanField(default=False, help_text="No checklist for this visit — the note above is all the assignee sees, and the public page shows a plain 'no checklist' message instead of an empty one. Set at creation only (see visit_create); build_checklist_items() short-circuits to an empty list for a visit with this set, so the periodic checklist refresh leaves it alone rather than quietly filling it back in from the visit type's real checklist."),
        ),
    ]
