# Generated by Django 6.0.8 on 2026-09-24 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0050_visit_no_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='calendar_override_note',
            field=models.CharField(blank=True, help_text='Set when the reservation calendar moved the visit off a date a person had chosen.', max_length=300),
        ),
        migrations.AddField(
            model_name='visit',
            name='date_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='date_set_by',
            field=models.ForeignKey(blank=True, help_text='Who moved this visit to a date of their own choosing (blank while the date is just what the calendar said).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
