# Generated by Django 6.0.8 on 2026-09-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0051_visit_date_set_by_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutbatch',
            name='breakdown_ok',
            field=models.BooleanField(help_text='True when its lines add up to the amount; False when they do not; blank when no lines were found for it.', null=True),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='items_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the lines that make it up add to (should equal the amount).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='sequence',
            field=models.CharField(blank=True, help_text="Whether its lines were the rows after it in the file ('after') or above it ('before').", max_length=6),
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uid', models.CharField(blank=True, help_text='The confirmation code on the line, if it had one.', max_length=80)),
                ('type_label', models.CharField(help_text="The platform's own word for the line (Reservation, Pass Through Tot, Resolution Payout ...).", max_length=80)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_name', models.CharField(blank=True, max_length=200)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_items', to='onsite.booking')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onsite.payoutbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
