# Generated by Django 6.0.8 on 2026-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsite', '0052_payout_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutbatch',
            name='sequence',
            field=models.CharField(blank=True, help_text="Whether its lines were the rows after it in the file ('after'), above it ('before'), or VRBO reservations grouped by payout date and listing ('grouped').", max_length=10),
        ),
    ]
