# Generated by Django 6.0.7 on 2026-07-26 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0026_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='tickets.ticket')),
                ('process_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='processes.processtemplate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_upload', models.BooleanField(default=False)),
                ('action_type', models.CharField(blank=True, default='', max_length=20)),
                ('document_key', models.CharField(blank=True, max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_datetime', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_dial_in', models.CharField(blank=True, max_length=200)),
                ('calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('calendar_id', models.CharField(blank=True, max_length=200)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='processes.processinstance')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInstanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='processes.processinstanceitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='process_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='processes.processinstanceitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_upload', models.BooleanField(default=False, help_text="Can't be checked until at least one file is attached to this step on the instance (e.g. a signed affidavit, a photo of a physically-posted notice).")),
                ('action_type', models.CharField(blank=True, choices=[('', 'Plain checkbox'), ('google_meet', 'Schedule Google Meet'), ('document_template', 'Prefilled document template'), ('email_link', 'Link to email compose')], default='', max_length=20)),
                ('document_key', models.CharField(blank=True, help_text="Only used when action_type is 'document_template' — e.g. 'board_meeting_notice'.", max_length=100)),
                ('process_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='processes.processtemplate')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='process_template_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('process_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='processes.processtemplate')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='processes.processtemplateitem')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
