# Generated by Django 6.0.7 on 2026-07-26 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contactdocument'),
        ('processes', '0002_generalize_processes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processrunstep',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processtemplatestep',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='process_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='processes.processtemplate'),
        ),
        migrations.AlterField(
            model_name='processrunstep',
            name='response',
            field=models.JSONField(blank=True, default=dict, help_text='The recorded value/output for this step — shape depends on step_type, see StepType docstring.'),
        ),
        migrations.AlterField(
            model_name='processrunstep',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.processrun'),
        ),
        migrations.AlterField(
            model_name='processrunstep',
            name='step_key',
            field=models.SlugField(max_length=60),
        ),
        migrations.AlterField(
            model_name='processrunstep',
            name='step_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('checklist', 'Checklist'), ('short_text', 'Short text'), ('long_text', 'Long text / notes'), ('number_currency', 'Number / currency'), ('date_time', 'Date and time'), ('dropdown_multiselect', 'Dropdown / multi-select'), ('record_selector', 'Record selector'), ('document_upload', 'Document upload'), ('photo_video_upload', 'Photo / video upload'), ('digital_signature', 'Digital signature'), ('task_assignment', 'Task assignment'), ('approval_decision', 'Approval / decision'), ('email_text_action', 'Email / text action'), ('calendar_event', 'Calendar event'), ('calculation_formula', 'Calculation / formula'), ('wait_timer', 'Wait / timer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='category',
            field=models.CharField(blank=True, help_text='Freeform grouping for the template list, e.g. "Association", "Short-Term Rental".', max_length=100),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='assignee_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting'), ('external', 'External party')], help_text='Who performs this step — a department, or "External party" for a step sent via a secure link. Mirrors Ticket.assigned_role/assigned_staff\'s existing dual-field shape.', max_length=20),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='assignee_staff',
            field=models.ForeignKey(blank=True, help_text='Optional specific-person override of assignee_role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staffprofile'),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Step-type-specific settings — shape depends on step_type, see StepType docstring.'),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='deadline_days_after_start',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Days after the run starts that this step is due.', null=True),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='process_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.processtemplate'),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='requires_upload',
            field=models.BooleanField(default=False, help_text="Can't be marked complete until at least one file is attached to this step on the run (e.g. a signed affidavit, a photo of a physically-posted notice) — independent of step_type, so even a plain checkbox step can require proof."),
        ),
        migrations.AlterField(
            model_name='processtemplatestep',
            name='step_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('checklist', 'Checklist'), ('short_text', 'Short text'), ('long_text', 'Long text / notes'), ('number_currency', 'Number / currency'), ('date_time', 'Date and time'), ('dropdown_multiselect', 'Dropdown / multi-select'), ('record_selector', 'Record selector'), ('document_upload', 'Document upload'), ('photo_video_upload', 'Photo / video upload'), ('digital_signature', 'Digital signature'), ('task_assignment', 'Task assignment'), ('approval_decision', 'Approval / decision'), ('email_text_action', 'Email / text action'), ('calendar_event', 'Calendar event'), ('calculation_formula', 'Calculation / formula'), ('wait_timer', 'Wait / timer')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProcessRunExternalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_step_keys', models.JSONField(blank=True, default=list, help_text='step_key values this link may see/act on. Empty list means every step on the run whose assignee_role is "external".')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('external_contact', models.ForeignKey(blank=True, help_text='Who this link was generated for, for the audit trail — not required for access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='processes.processrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
