# Generated by Django 6.0.7 on 2026-08-20 12:53

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_processrunstep_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processattachment',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='process_attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='processtemplateattachment',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='process_template_attachments/%Y/%m/'),
        ),
    ]
