from django.urls import path

from . import views

urlpatterns = [
    path('calendar/connect/', views.calendar_connect, name='calendar_connect'),
    path('calendar/callback/', views.calendar_callback, name='calendar_callback'),
    path('calendar/disconnect/', views.calendar_disconnect, name='calendar_disconnect'),
    path('calendar/select/', views.calendar_select, name='calendar_select'),
    path('calendar/events/new/', views.calendar_event_create, name='calendar_event_create'),
    path('calendar/events/update/', views.calendar_event_update, name='calendar_event_update'),
    path('calendar/events/delete/', views.calendar_event_delete, name='calendar_event_delete'),
    path('calendar/timezone/', views.timezone_select, name='timezone_select'),
    path('quickbooks/connect/', views.quickbooks_connect, name='quickbooks_connect'),
    path('quickbooks/callback/', views.quickbooks_callback, name='quickbooks_callback'),
    path('quickbooks/disconnect/', views.quickbooks_disconnect, name='quickbooks_disconnect'),
    path('admin-tools/', views.admin_tools, name='admin_tools'),
    path('admin-tools/properties/<int:pk>/toggle/', views.property_toggle_active, name='property_toggle_active'),
    path('admin-tools/settings/save/', views.admin_settings_save, name='admin_settings_save'),
    path('admin-tools/settings/test-email/', views.admin_test_email_send, name='admin_test_email_send'),
    path('admin-tools/phone-settings/save/', views.admin_phone_settings_save, name='admin_phone_settings_save'),
    path('admin-tools/staff/new/', views.staff_create, name='staff_create'),
    path(
        'admin-tools/staff/<int:pk>/toggle-company-admin/', views.staff_toggle_company_admin,
        name='staff_toggle_company_admin',
    ),
    path('properties/', views.property_list, name='property_list'),
    path('properties/new/', views.property_create, name='property_create'),
    path('properties/<int:pk>/', views.property_detail, name='property_detail'),
    path('properties/<int:pk>/edit/', views.property_edit, name='property_edit'),
    path('properties/<int:pk>/recurring-tasks/', views.property_recurring_tasks, name='property_recurring_tasks'),
    path('properties/<int:pk>/followup/sms/', views.property_followup_sms, name='property_followup_sms'),
    path('properties/<int:pk>/followup/email/', views.property_followup_email, name='property_followup_email'),
    path('properties/<int:pk>/contacts/<int:contact_pk>/thread/', views.property_contact_thread, name='property_contact_thread'),
    path('properties/address-autocomplete/', views.property_address_autocomplete, name='property_address_autocomplete'),
    path('properties/address-lookup/<str:place_id>/', views.property_address_lookup, name='property_address_lookup'),
    path('contacts/', views.contact_list, name='contact_list'),
    path('contacts/new/', views.contact_create, name='contact_create'),
    path('contacts/import/parse/', views.contact_import_parse, name='contact_import_parse'),
    path('contacts/import/commit/', views.contact_import_commit, name='contact_import_commit'),
    path('contacts/<int:pk>/edit/', views.contact_edit, name='contact_edit'),
    path('contacts/<int:pk>/delete/', views.contact_delete, name='contact_delete'),
    path('contacts/review/', views.contact_review, name='contact_review'),
    path('contacts/review/clear-all/', views.contact_candidates_clear_all, name='contact_candidates_clear_all'),
    path('contacts/review/bulk-save/', views.contact_review_bulk_save, name='contact_review_bulk_save'),
    path('contacts/review/<int:pk>/approve/', views.contact_review_approve, name='contact_review_approve'),
    path('contacts/review/<int:pk>/reject/', views.contact_review_reject, name='contact_review_reject'),
    path('contacts/updates/<int:pk>/apply/', views.contact_update_apply, name='contact_update_apply'),
    path('contacts/updates/<int:pk>/dismiss/', views.contact_update_dismiss, name='contact_update_dismiss'),
    path('contacts/duplicates/', views.contact_duplicates, name='contact_duplicates'),
    path('contacts/duplicates/merge/', views.contact_duplicates_merge, name='contact_duplicates_merge'),
    path('contacts/duplicates/dismiss/', views.contact_duplicates_dismiss, name='contact_duplicates_dismiss'),
]
