# Generated by Django 6.0.7 on 2026-08-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_propertylistingname_and_more'),
        ('tickets', '0033_alter_ticket_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], help_text="Which queue this rule's sessions file under for filtering/dashboards — independent of owner (a person's own StaffProfile.role may differ from the department their session work should be grouped under).", max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('monthly_workday', 'Monthly (by working day)'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('workday_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Only used when frequency is "Monthly (by working day)" — e.g. 3 means the 3rd Mon-Fri business day of the month. Weekends are skipped; holidays are not currently accounted for (no holiday calendar configured) — a rule using this frequency can land on a recognized holiday.', null=True)),
                ('next_open_date', models.DateField(help_text='The next date a session should open for this rule.')),
                ('due_offset_days', models.PositiveSmallIntegerField(default=0, help_text='How many days after opening a session is due — 0 means due the same day.')),
                ('active_from', models.DateField(blank=True, help_text='No sessions open before this date. Blank = no start limit.', null=True)),
                ('active_until', models.DateField(blank=True, help_text='No sessions open after this date. Blank = no end limit — use this for seasonal rules (e.g. snowbird season) instead of deactivating and reactivating the rule by hand.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_source', models.CharField(choices=[('static', 'Static list'), ('query', 'Property query')], default='static', max_length=10)),
                ('property_types', models.JSONField(blank=True, default=list, help_text='Only used when Line source is "Property query" — Property.Type codes a property must match (e.g. ["str", "commercial"]). Empty = every active property type.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text="The person this rule's sessions belong to — snapshotted onto Session.owner at creation, so reassigning the template later only affects future sessions.", on_delete=django.db.models.deletion.PROTECT, related_name='session_templates', to='core.staffprofile')),
                ('required_attributes', models.ManyToManyField(blank=True, help_text='Only used when Line source is "Property query" — a matching property must have ALL of these tags. Empty = no constraint.', related_name='required_by_session_templates', to='core.propertyattribute')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], help_text='Snapshotted from template.department at creation.', max_length=20)),
                ('period_label', models.CharField(help_text='Human display, e.g. "August 2026" or "Tue 4 Aug" — never parsed.', max_length=100)),
                ('period_key', models.DateField(help_text='The occurrence date this session represents — the real identity of "which period," compared for uniqueness below. period_label is just its display form.')),
                ('opens_at', models.DateField()),
                ('due_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted')], default='open', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Snapshotted from template.owner at creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.staffprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='worksessions.sessiontemplate')),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_lines', to='worksessions.sessiontemplate')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.CharField(blank=True, help_text='Required whenever state is Skipped or Not applicable — without one, a skipped line can\'t be told apart from "the rule is noise" versus "the property was vacant," and every drift signal downstream depends on that distinction.', max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('promoted_ticket', models.ForeignKey(blank=True, help_text='Set when this line was promoted to a real Ticket because something went wrong — the exception path, mirroring onsite.VisitIssue.created_ticket. Sessions do not create tickets by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_session_line', to='tickets.ticket')),
                ('property', models.ForeignKey(blank=True, help_text='Set only for a query-driven line — the property it was generated for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_lines', to='core.property')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='worksessions.session')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['skipped', 'not_applicable']), _negated=True), models.Q(('skip_reason', ''), _negated=True), _connector='OR'), name='session_line_skip_reason_required')],
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('template', 'period_key'), name='uniq_session_template_period'),
        ),
    ]
