# Generated by Django 6.0.7 on 2026-08-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_propertylistingname_unit'),
        ('worksessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionline',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Set only for a query-driven line generated per-unit rather than per-property — see SessionTemplate.line_source and generation.py::matching_targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_lines', to='core.unit'),
        ),
        migrations.AddField(
            model_name='sessiontemplate',
            name='query_by_unit',
            field=models.BooleanField(default=False, help_text='Only used when Line source is "Property query" — when a matching property has Units, generate one line per Unit instead of one line for the whole property (a matching property with no units still gets a single property-level line either way). Off by default so existing property-query rules keep their exact current behavior unchanged.'),
        ),
    ]
