# Generated by Django 6.0.8 on 2026-09-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksessions', '0002_sessionline_unit_sessiontemplate_query_by_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontemplate',
            name='link_url',
            field=models.URLField(blank=True, help_text='A web address for the task (a bank, a utility, a portal) — opens in a new tab from the session.', max_length=500),
        ),
        migrations.AddField(
            model_name='sessiontemplate',
            name='login_username',
            field=models.CharField(blank=True, help_text='The username or email to sign in with.', max_length=200),
        ),
        migrations.AddField(
            model_name='sessiontemplate',
            name='password_hint',
            field=models.CharField(blank=True, help_text='A reminder of the password, not the password itself — e.g. "the usual one, with the year at the end".', max_length=300),
        ),
    ]
