# Generated by Django 6.0.7 on 2026-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='source_reference',
            field=models.CharField(blank=True, help_text='External event id (e.g. email message id) this was parsed from, for idempotent re-polling.', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='supplyrequest',
            unique_together={('property', 'source_reference', 'item_guess')},
        ),
    ]
