# Generated by Django 6.0.7 on 2026-07-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_supplyrequest_source_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyorderbatch',
            options={'ordering': ['-date'], 'verbose_name_plural': 'supply order batches'},
        ),
    ]
