# Generated by Django 6.0.7 on 2026-07-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('supplies', '0003_alter_supplyorderbatch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='property',
            field=models.ForeignKey(blank=True, help_text="Blank when the source (e.g. a shared Quo phone line) can't determine which property.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='core.property'),
        ),
    ]
