# Generated by Django 6.0.7 on 2026-08-05 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_propertylistingname_and_more'),
        ('onsite', '0013_booking_listing_name'),
        ('supplies', '0004_alter_supplyrequest_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_label', models.CharField(blank=True, help_text='e.g. "ct", "ea", "oz" — shown next to quantity, not enforced.', max_length=20)),
                ('walmart_item_id', models.CharField(blank=True, help_text='Walmart\'s numeric item id for the exact product to buy — e.g. from the product page URL or the "Share" link. Blank is allowed at catalog-entry time (a property can stock an item before someone\'s picked the exact Walmart listing for it) but a PropertySupply row referencing an item with no id here is surfaced as a catalog problem on the cart page, never silently dropped from the order.', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_quantity', models.PositiveIntegerField(default=1, help_text='How many to buy when this reads below par.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order this item appears in the par check.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='core.property')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_supplies', to='supplies.supplyitem')),
            ],
            options={
                'verbose_name_plural': 'property supplies',
                'ordering': ['property', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text="Set optimistically the moment staff click through to Walmart — clicking doesn't prove a purchase happened, but this is what suppresses the item from tomorrow's cart, and the reading loop self-corrects either way: if the order never actually completed, the next reading is still below par and the item returns, flagged. Undo-able by staff, which just clears this back to null.", null=True)),
                ('cart_url', models.TextField(blank=True, help_text='The generated Walmart addToCart URL(s) for this order. More than one, newline-separated, only if the item count pushed a single URL past a safe length.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('low', 'Low')], max_length=10)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('property_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='supplies.propertysupply')),
                ('read_by_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
                ('read_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staffprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_readings', to='onsite.visit')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplies.supplyorder')),
                ('property_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='supplies.propertysupply')),
                ('triggered_by_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='supplies.supplyreading')),
            ],
        ),
        migrations.AddConstraint(
            model_name='propertysupply',
            constraint=models.UniqueConstraint(fields=('property', 'supply_item'), name='uniq_property_supply_item'),
        ),
        migrations.AddConstraint(
            model_name='supplyreading',
            constraint=models.CheckConstraint(condition=models.Q(('read_by_staff__isnull', True), ('read_by_contact__isnull', True), _connector='OR'), name='supplyreading_single_reader'),
        ),
    ]
