# Generated by Django 6.0.7 on 2026-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_propertylistingname_and_more'),
        ('onsite', '0013_booking_listing_name'),
        ('supplies', '0005_supplyitem_propertysupply_supplyorder_supplyreading_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplyreading',
            constraint=models.UniqueConstraint(fields=('property_supply', 'visit'), name='uniq_reading_per_visit_per_item'),
        ),
    ]
