# Generated by Django 6.0.7 on 2026-08-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_contactdocument_file_and_more'),
        ('supplies', '0006_supplyreading_uniq_reading_per_visit_per_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertysupply',
            options={'ordering': ['property', 'unit__label', 'display_order'], 'verbose_name_plural': 'property supplies'},
        ),
        migrations.RemoveConstraint(
            model_name='propertysupply',
            name='uniq_property_supply_item',
        ),
        migrations.AddField(
            model_name='propertysupply',
            name='unit',
            field=models.ForeignKey(blank=True, help_text="Leave blank for a property-wide item (or a single-unit property). Set to track this item's par level independently for one specific unit.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='core.unit'),
        ),
        migrations.AddConstraint(
            model_name='propertysupply',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'supply_item'), name='uniq_property_supply_item_no_unit'),
        ),
        migrations.AddConstraint(
            model_name='propertysupply',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'supply_item'), name='uniq_unit_supply_item'),
        ),
    ]
