# Hand-written (not autogenerated) — the redesign deletes PropertySupply
# entirely and restructures SupplyReading/SupplyOrderLine to reference
# property/unit/supply_item directly instead of through it, which
# `makemigrations --no-input` can't resolve on its own (it needs a
# default for the new non-nullable FKs, and there's no sane universal
# default for "which supply item is this row for").
#
# Depends on 0008 (a separate migration/transaction) having already
# cleared PropertySupply/SupplyReading/SupplyOrder/SupplyOrderLine rows —
# see that migration's own comment for why the data-clear and the schema
# changes below can't share one transaction on Postgres. By the time this
# runs, every table this touches is already empty, so adding the new
# required fields nullable-then-NOT-NULL below never has real rows to
# violate. SupplyItem itself (name/unit_label/walmart_item_id/is_active)
# is only ever gaining fields here, never recreated, so every existing
# item — Walmart IDs included — passes through untouched.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_contactdocument_file_and_more'),
        ('onsite', '0013_booking_listing_name'),
        ('supplies', '0008_clear_supply_operational_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='is_standard',
            field=models.BooleanField(
                default=False,
                help_text='On the portfolio-wide standard list — every property/unit stocks this '
                           'automatically, no per-property setup required. Uncheck instead of '
                           'deactivating if a few properties still need it added manually as an extra '
                           "(see PropertySupplyOverride) but most no longer do.",
            ),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='standard_reorder_quantity',
            field=models.PositiveIntegerField(
                default=1,
                help_text='Default "how many to buy when this reads below par" for every property/unit '
                           'following the standard list. A specific property/unit can still override this '
                           '— see PropertySupplyOverride.reorder_quantity. Ignored when is_standard is off.',
            ),
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='standard_display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order this item appears in the standard list / par check.'),
        ),

        migrations.CreateModel(
            name='PropertySupplyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, help_text="This property/unit doesn't stock this standard item at all.")),
                ('reorder_quantity', models.PositiveIntegerField(
                    blank=True, null=True,
                    help_text='How many to buy when below par. Overrides the standard quantity for a '
                               'standard item; required (the only source of quantity) for a non-standard '
                               '"extra" item. Irrelevant when is_hidden is set.',
                )),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order an "extra" item appears in the par check.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_overrides', to='core.property')),
                ('unit', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_overrides',
                    to='core.unit', help_text='Leave blank to apply to the whole property (every unit). Set to override just one unit.',
                )),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_overrides', to='supplies.supplyitem')),
            ],
            options={
                'ordering': ['property', 'unit__label', 'display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='propertysupplyoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'supply_item'), name='uniq_property_override_no_unit'),
        ),
        migrations.AddConstraint(
            model_name='propertysupplyoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('unit', 'supply_item'), name='uniq_unit_override'),
        ),

        # --- SupplyOrderLine: property_supply -> unit (attribution only) + supply_item (direct) ---
        migrations.AddField(
            model_name='supplyorderline',
            name='unit',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_order_lines', to='core.unit',
            ),
        ),
        migrations.AddField(
            model_name='supplyorderline',
            name='supply_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='supplies.supplyitem'),
        ),
        migrations.AlterField(
            model_name='supplyorderline',
            name='supply_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='supplies.supplyitem'),
        ),
        migrations.RemoveField(model_name='supplyorderline', name='property_supply'),

        # --- SupplyReading: property_supply -> property/unit/supply_item direct ---
        migrations.AddField(
            model_name='supplyreading',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_readings', to='core.property'),
        ),
        migrations.AlterField(
            model_name='supplyreading',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_readings', to='core.property'),
        ),
        migrations.AddField(
            model_name='supplyreading',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_readings', to='core.unit'),
        ),
        migrations.AddField(
            model_name='supplyreading',
            name='supply_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='supplies.supplyitem'),
        ),
        migrations.AlterField(
            model_name='supplyreading',
            name='supply_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='supplies.supplyitem'),
        ),
        migrations.RemoveConstraint(model_name='supplyreading', name='uniq_reading_per_visit_per_item'),
        migrations.RemoveField(model_name='supplyreading', name='property_supply'),
        migrations.AddConstraint(
            model_name='supplyreading',
            constraint=models.UniqueConstraint(fields=('property', 'unit', 'supply_item', 'visit'), name='uniq_reading_per_visit_per_item'),
        ),

        migrations.DeleteModel(name='PropertySupply'),

        migrations.AlterField(
            model_name='supplyitem',
            name='walmart_item_id',
            field=models.CharField(
                blank=True, max_length=32,
                help_text='Walmart\'s numeric item id for the exact product to buy — e.g. from the product '
                           'page URL or the "Share" link. Blank is allowed at catalog-entry time but an item '
                           'with no id here is surfaced as a catalog problem on the cart page, never silently '
                           'dropped from the order.',
            ),
        ),
    ]
