"""Tells whoever an on-site visit is assigned to, with the link they work it
from. A visit isn't a Ticket or Property, so messaging.services.
send_followup_bulk (which requires exactly one of those) doesn't fit here —
this goes straight to the same underlying primitives it uses
(send_via_quo/get_sms_backend for SMS, send_mail for email) instead of
adding a second messaging abstraction.

No FollowUpLog row gets written — that model is ticket-or-property scoped
too (see its CheckConstraint), and a visit assignment ping is closer to
the vendor-completion-link SMS (a one-off notice, not a tracked
conversation) than to the Follow-Up modal's logged correspondence.

WHEN the link goes out (dispatch_link): the day before the visit, from
settings.ONSITE_LINK_SEND_HOUR (8 AM local) on — unless the visit is dated
today, or was created/assigned after that hour the day before, in which case
it goes straight away. Everything that assigns a visit (the new-visit form,
reassigning, a recurring rule, a booking-created visit that gets a cleaner
later) calls dispatch_link; a timer (send_due_visit_links) sends the ones
that were waiting for their day. Each visit remembers who it has told and
for which date (Visit.link_notified_key), so nobody is texted twice for the
same visit, and a reassignment or a moved date tells the right person again."""
import logging
from datetime import timedelta

from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse
from django.utils import timezone

logger = logging.getLogger(__name__)

SENT, SCHEDULED, NOT_NEEDED, FAILED = 'sent', 'scheduled', 'not_needed', 'failed'


def _assignee_contact_info(visit):
    """(name, phone, email) for whoever visit is currently assigned to, or
    (None, None, None) if unassigned. Staff get their phone from
    StaffProfile and email from the underlying User; a contact (external
    cleaner) carries both directly."""
    if visit.assigned_staff_id:
        staff = visit.assigned_staff
        name = staff.user.get_full_name() or staff.user.username
        return name, staff.phone, staff.user.email
    if visit.assigned_contact_id:
        contact = visit.assigned_contact
        return contact.name, contact.phone, contact.email
    return None, None, None


def notify_assignee(visit, request=None, updated=False):
    """Texts and emails whoever `visit` is assigned to, with the
    property/date and their token link. Best-effort and silent per
    channel: no phone on file just skips the text, no email just skips
    the email, and an actual send failure is logged, never raised —
    assigning a visit must never fail (or look like it failed) because a
    text couldn't go out. `request` is only used to build the link's
    address; without one (a visit generated by a recurring rule, off the
    scheduler) the address comes from settings.SITE_BASE_URL. `updated`
    prefixes the message when this person was already told something
    different (a moved date). Returns SENT (at least one channel went
    out), NOT_NEEDED (no one assigned, or nothing on file to send to), or
    FAILED (there was somewhere to send and every attempt failed)."""
    name, phone, email = _assignee_contact_info(visit)
    if not name or not (phone or email):
        return NOT_NEEDED

    path = reverse('onsite_visit_public', args=[visit.access_token])
    link = request.build_absolute_uri(path) if request is not None else f'{settings.SITE_BASE_URL}{path}'
    when = visit.scheduled_date.strftime('%A, %b %d') if visit.scheduled_date else 'a date to be confirmed'
    if visit.scheduled_start:
        when += f' at {visit.scheduled_start.strftime("%I:%M %p").lstrip("0")}'

    first_name = name.split()[0] if name else ''
    deep_clean_note = ' (deep clean)' if visit.is_deep_clean else ''
    body = (
        f'{"Update: " if updated else ""}Hi {first_name}, you\'re scheduled for a {visit.visit_type}{deep_clean_note} at '
        f'{visit.property.name} on {when}. Details: {link}'
    ).strip()

    delivered = False
    if phone:
        try:
            from messaging.services import get_sms_backend, send_via_quo
            if not send_via_quo(phone, body):
                get_sms_backend().send(phone, body)
            delivered = True
        except Exception:
            logger.exception('Failed to text visit assignment (visit %s) to %s', visit.pk, phone)

    if email:
        try:
            send_mail(
                f'On-site visit — {visit.property.name}', body,
                settings.DEFAULT_FROM_EMAIL, [email],
            )
            delivered = True
        except Exception:
            logger.exception('Failed to email visit assignment (visit %s) to %s', visit.pk, email)
    return SENT if delivered else FAILED


# --- when the link goes out ------------------------------------------------------

def link_key(visit):
    """Who the link is for and which date it describes."""
    if visit.assigned_staff_id:
        who = f's{visit.assigned_staff_id}'
    elif visit.assigned_contact_id:
        who = f'c{visit.assigned_contact_id}'
    else:
        return ''
    return f'{who}|{visit.scheduled_date.isoformat() if visit.scheduled_date else ""}'


def link_due(visit, now=None):
    """Whether the cleaner should have the link by `now`: always for a visit
    dated today; for tomorrow's, from the send hour onward; never for a
    later date (not yet) or a past one (a visit that's over is never
    announced) or one with no date."""
    local = timezone.localtime(now or timezone.now())
    today = local.date()
    if visit.scheduled_date is None or visit.scheduled_date < today:
        return False
    if visit.scheduled_date == today:
        return True
    if visit.scheduled_date == today + timedelta(days=1):
        return local.hour >= settings.ONSITE_LINK_SEND_HOUR
    return False


def link_send_description(visit):
    """Plain-language 'when will they get it' for a flash message, e.g.
    "on Fri, Oct 2 at 8 AM"."""
    if visit.scheduled_date is None:
        return "once the visit has a date"
    send_day = visit.scheduled_date - timedelta(days=1)
    hour = settings.ONSITE_LINK_SEND_HOUR
    clock = f'{hour % 12 or 12} {"AM" if hour < 12 else "PM"}'
    return f'on {send_day:%a, %b} {send_day.day} at {clock}'


def dispatch_link(visit, request=None, now=None):
    """Sends this visit's link to its assignee if it's due, otherwise leaves
    it for the timer. Returns SENT, SCHEDULED (assigned, but not due yet),
    NOT_NEEDED (nobody assigned, wrong status, or they already have it for
    this assignee/date) or FAILED (nothing got through; it will be retried).
    Never raises."""
    from ..models import Visit

    try:
        fresh = Visit.objects.select_related(
            'property', 'unit', 'visit_type', 'assigned_staff__user', 'assigned_contact',
        ).filter(pk=visit.pk).first()
        if fresh is None or fresh.status != Visit.Status.SCHEDULED:
            return NOT_NEEDED
        key = link_key(fresh)
        if not key or fresh.link_notified_key == key:
            return NOT_NEEDED
        if not link_due(fresh, now):
            return SCHEDULED

        # Claim before sending, so a save and the timer running at the same
        # moment can't both send it. Restored if nothing got through.
        previous_key, previous_at = fresh.link_notified_key, fresh.link_notified_at
        claimed = Visit.objects.filter(pk=fresh.pk).exclude(link_notified_key=key).update(
            link_notified_key=key, link_notified_at=timezone.now(),
        )
        if not claimed:
            return NOT_NEEDED
        result = notify_assignee(fresh, request, updated=bool(previous_key))
        if result == FAILED:
            Visit.objects.filter(pk=fresh.pk).update(link_notified_key=previous_key, link_notified_at=previous_at)
            return FAILED
        return SENT if result == SENT else NOT_NEEDED
    except Exception:
        logger.exception('Unexpected error sending the link for visit %s', getattr(visit, 'pk', visit))
        return FAILED


def send_due_visit_links(now=None):
    """The timer's half: every scheduled visit dated today or tomorrow whose
    assignee hasn't been sent the link for this assignee/date yet. Returns
    {'sent': n, 'failed': n}."""
    from ..models import Visit

    local_today = timezone.localtime(now or timezone.now()).date()
    counts = {SENT: 0, FAILED: 0}
    candidates = Visit.objects.filter(
        status=Visit.Status.SCHEDULED, scheduled_date__gte=local_today, scheduled_date__lte=local_today + timedelta(days=1),
    ).filter(assigned_staff__isnull=False) | Visit.objects.filter(
        status=Visit.Status.SCHEDULED, scheduled_date__gte=local_today, scheduled_date__lte=local_today + timedelta(days=1),
        assigned_contact__isnull=False,
    )
    for visit in candidates.distinct():
        result = dispatch_link(visit, now=now)
        if result in counts:
            counts[result] += 1
    return {'sent': counts[SENT], 'failed': counts[FAILED]}
