# Generated by Django 6.0.7 on 2026-08-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0036_staffprofile_is_portfolio_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(blank=True, default='briefcase', help_text='A lucide-icons name (e.g. "briefcase", "home", "package") shown on its dashboard box.', max_length=40)),
                ('custom_field_label', models.CharField(blank=True, help_text='Optional — set a label (e.g. "Account #") to show one extra free-text field on every task under this business. Blank = no extra field.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_staff', models.ManyToManyField(blank=True, help_text="Staff besides the owner allowed into THIS business's own sub-dashboard only (not the combined /portfolio/ view, which stays owner-only). Empty by default — a hook for later, e.g. a bookkeeper on one specific business.", related_name='shared_businesses', to='core.staffprofile')),
                ('owner', models.ForeignKey(help_text='Always the portfolio owner today — see StaffProfile.is_portfolio_owner.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to='core.staffprofile')),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BizRecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Used as the generated task's title each time.", max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_field_value', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly_day', 'Monthly (on a specific day)'), ('monthly_workday', 'Monthly (by working day)'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Only used when frequency is "Monthly (on a specific day)" — 1-31. A month shorter than the chosen day (e.g. 31 in April) lands on that month\'s last real day instead.', null=True)),
                ('workday_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Only used when frequency is "Monthly (by working day)" — e.g. 3 means the 3rd Mon-Fri business day of the month. Weekends are skipped; holidays are not accounted for.', null=True)),
                ('next_due_date', models.DateField(help_text='The next date this rule should generate a task for.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='portfolio.business')),
            ],
            options={
                'ordering': ['business', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portfolio.business')),
            ],
            options={
                'verbose_name_plural': 'business categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BizTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional dollar amount — e.g. a bill total. Blank when not relevant.', max_digits=10, null=True)),
                ('custom_field_value', models.CharField(blank=True, help_text='Shown/labeled only when business.custom_field_label is set.', max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_rule', models.ForeignKey(blank=True, help_text='Set when this task was generated by a recurring rule; blank for a one-off task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='portfolio.bizrecurringrule')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='portfolio.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='portfolio.businesscategory')),
            ],
            options={
                'ordering': ['business', 'due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bizrecurringrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='portfolio.businesscategory'),
        ),
        migrations.AddConstraint(
            model_name='businesscategory',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='uniq_bizcategory_business_name'),
        ),
    ]
