# Generated by Django 6.0.7 on 2026-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_dedupe_biztask_rule_due_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='biztask',
            constraint=models.UniqueConstraint(fields=('recurring_rule', 'due_date'), name='uniq_biztask_rule_due_date'),
        ),
    ]
