# Generated by Django 6.0.7 on 2026-07-20 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(default='generic', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('quo_call', 'Phone (Quo)'), ('calendar', 'Calendar'), ('airbnb', 'Airbnb'), ('vrbo', 'VRBO'), ('fake', 'Simulated (dev)'), ('recurring', 'Recurring template')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Stable external id (e.g. reservation confirmation code, email message id).', max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateField(blank=True, help_text='For recurring tickets: the occurrence date this instance represents.', null=True)),
                ('completion_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('completion_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_contact', models.ForeignKey(blank=True, help_text='Use for reassigning to an external vendor/contractor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='core.contact')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='core.staffprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'Text message')], max_length=10)),
                ('sent_to', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
                ('from_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staffprofile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='tickets.ticket')),
                ('to_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
                ('to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staffprofile')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by_contact', models.ForeignKey(blank=True, help_text='Set when an external vendor uploaded this via the completion link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(default='generic', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_run_date', models.DateField(help_text='The next date this task should be generated for.')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('skip_missed', models.BooleanField(default=False, help_text='If the scheduler was down and occurrences were missed, jump straight to the next future occurrence instead of backfilling every missed one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_templates', to='core.staffprofile')),
                ('property', models.ForeignKey(blank=True, help_text='Leave blank to generate this task for every active property.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_templates', to='core.property')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tickets', to='tickets.tickettemplate'),
        ),
        migrations.CreateModel(
            name='TicketContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reporter', 'Reporter (follow up here)'), ('cc', 'CC'), ('other', 'Other')], default='other', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='core.contact')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_contacts', to='tickets.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'contact', 'role')},
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_reference', ''), _negated=True), models.Q(('status', 'cancelled'), _negated=True)), fields=('source', 'source_reference', 'kind'), name='uniq_active_ticket_source_ref_kind'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('created_from_template__isnull', False)), fields=('created_from_template', 'scheduled_for'), name='uniq_template_scheduled_for'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_staff__isnull', True), ('assigned_contact__isnull', True), _connector='OR'), name='ticket_single_assignee'),
        ),
    ]
