# Generated by Django 6.0.7 on 2026-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='uniq_template_scheduled_for',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('created_from_template__isnull', False)), fields=('created_from_template', 'scheduled_for', 'property'), name='uniq_template_scheduled_for_property'),
        ),
    ]
