# Generated by Django 6.0.7 on 2026-07-20 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0002_remove_ticket_uniq_template_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='property',
            field=models.ForeignKey(blank=True, help_text="Blank when the source (e.g. a shared Quo phone line) can't determine which property this is about — staff assigns it manually.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.property'),
        ),
    ]
