# Generated by Django 6.0.7 on 2026-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], help_text='The team/queue this ticket belongs to. Set automatically for reactive tickets when no specific person can be determined yet; a specific assigned_staff can still be set alongside it once someone claims it.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('quo', 'Phone (Quo)'), ('calendar', 'Calendar'), ('airbnb', 'Airbnb'), ('vrbo', 'VRBO'), ('fake', 'Simulated (dev)'), ('recurring', 'Recurring template')], default='manual', max_length=20),
        ),
    ]
