# Generated by Django 6.0.7 on 2026-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_assigned_role_alter_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='default_assigned_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], default='property_manager', help_text='Every recurring ticket belongs to a team; a specific person is optional on top of that.', max_length=20),
        ),
    ]
