# Generated by Django 6.0.7 on 2026-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tickettemplate_default_assigned_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('vendor', 'Vendor'), ('billing', 'Billing'), ('admin', 'Admin'), ('supply', 'Supply'), ('other', 'Other')], default='other', help_text='What kind of issue this is, at a glance.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='raw_context',
            field=models.TextField(blank=True, help_text='Full original text (e.g. a Quo conversation transcript) — kept for reference on the ticket detail page, never shown in list views.'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='default_category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('vendor', 'Vendor'), ('billing', 'Billing'), ('admin', 'Admin'), ('supply', 'Supply'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, help_text='One concise sentence. Full source context goes in raw_context.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(help_text='A short, scannable headline — not a full sentence.', max_length=200),
        ),
    ]
