# Generated by Django 6.0.7 on 2026-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_category_ticket_raw_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tickettemplate',
            name='default_category',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], help_text='The department/queue this ticket belongs to — the primary classification for every ticket. Set automatically for reactive tickets when no specific person can be determined yet; a specific assigned_staff can still be set alongside it once someone claims it.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='default_assigned_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], default='property_manager', help_text='Every recurring ticket belongs to a department; a specific person is optional on top of that.', max_length=20),
        ),
    ]
