# Generated by Django 6.0.7 on 2026-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='workday_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Only used when frequency is "Monthly (by working day)" — e.g. 3 means the 3rd Mon–Fri business day of the month (weekends skipped, holidays not currently accounted for).', null=True),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('monthly_workday', 'Monthly (by working day)'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
