# Generated by Django 6.0.7 on 2026-07-23 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_propertyattribute_propertyattributeassignment'),
        ('tickets', '0008_tickettemplate_workday_of_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='approval_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], max_length=20),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='escalation_threshold_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Flag (not reassign) an instance once it is overdue by this many days.', null=True),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0, help_text="Generate the instance this many days before it's due, in status Upcoming."),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='property_types',
            field=models.JSONField(blank=True, default=list, help_text='Property.Type codes this applies to (e.g. ["str", "commercial"]). Empty = every type. JSONField (not ArrayField) so this works on SQLite dev and Postgres prod alike.'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='required_attributes',
            field=models.ManyToManyField(blank=True, help_text='Property must have ALL of these tags for this template to auto-apply. Empty = no constraint.', related_name='required_by_templates', to='core.propertyattribute'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Completing an instance moves it to Completed (submitted); a staff member with approval_role must then approve it to reach Verified.'),
        ),
        migrations.CreateModel(
            name='PackageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateField()),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_runs', to='core.property')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tickets.taskpackage')),
            ],
            options={
                'unique_together': {('package', 'property', 'scheduled_for')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='package_run',
            field=models.ForeignKey(blank=True, help_text='Groups this instance with its sibling steps in the same task package run — always null for one-off tickets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.packagerun'),
        ),
        migrations.CreateModel(
            name='TemplateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tickets.tickettemplate')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tickets.tickettemplate')),
            ],
            options={
                'unique_together': {('template', 'scheduled_for')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='template_occurrence',
            field=models.ForeignKey(blank=True, help_text='Groups this instance with its siblings generated from the same template for the same period, across every property — always null for one-off tickets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.templateoccurrence'),
        ),
        migrations.CreateModel(
            name='TicketChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tickets.ticket')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTemplateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('exclude', 'Exclude from this property'), ('include', 'Include / adjust for this property')], default='include', max_length=10)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('monthly_workday', 'Monthly (by working day)'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('workday_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], max_length=20)),
                ('next_run_date', models.DateField(blank=True, help_text="Only used when frequency is overridden — this property then advances on its own schedule instead of the template's shared cursor.", null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.staffprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_overrides', to='core.property')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_overrides', to='tickets.tickettemplate')),
            ],
            options={
                'unique_together': {('property', 'template')},
            },
        ),
        migrations.CreateModel(
            name='PropertyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.property')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to='tickets.taskpackage')),
            ],
            options={
                'unique_together': {('property', 'package')},
            },
        ),
        migrations.CreateModel(
            name='TaskPackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('depends_on', models.ForeignKey(blank=True, help_text="If set, generated instances of this step start Blocked until the referenced step's instance (same property, same period) reaches a completed-like status.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='tickets.taskpackagetemplate')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tickets.taskpackage')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_memberships', to='tickets.tickettemplate')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('package', 'template')},
            },
        ),
    ]
