# Generated by Django 6.0.7 on 2026-07-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_applicability_and_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_reason',
            field=models.CharField(blank=True, help_text='Why this was Skipped / Not applicable / Deferred — see REASON_REQUIRED_STATUSES.', max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('verified', 'Verified'), ('skipped', 'Skipped'), ('not_applicable', 'Not applicable'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
