# Generated by Django 6.0.7 on 2026-07-23 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact_source_contactimportcandidate'),
        ('tickets', '0010_ticket_status_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuplog',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Shared by every row created from one Follow-Up "Send" click, so the audit trail can render one line per send-action while keeping per-recipient success/failure.'),
        ),
        migrations.AddField(
            model_name='followuplog',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Who this specific row was sent to — null on rows predating this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.contact'),
        ),
        migrations.AddField(
            model_name='followuplog',
            name='is_group',
            field=models.BooleanField(default=False, help_text='True only for a combined group email (all recipients in one to: list) — SMS and individual email sends are always False, one physical send per row.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='followup_done',
            field=models.BooleanField(default=False, help_text='Set the first time any Follow-Up text or email successfully sends — never reset, so it just means "someone has been contacted at least once," not "up to date."'),
        ),
    ]
