# Generated by Django 6.0.7 on 2026-07-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_followuplog_batch_id_followuplog_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcontact',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter (follow up here)'), ('owner', 'Owner'), ('contractor', 'Contractor'), ('other', 'Additional contact')], default='other', max_length=20),
        ),
    ]
