# Generated by Django 6.0.7 on 2026-07-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contact_phone_alter_staffprofile_phone'),
        ('tickets', '0012_alter_ticketcontact_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Only used when Target type is "Contact" — generates this task for every property currently linked to this contact (Contact.properties).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_templates', to='core.contact'),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='target_type',
            field=models.CharField(choices=[('every_property', 'Every property'), ('property_category', 'Property category'), ('property', 'Specific property'), ('contact', 'Contact'), ('company', 'Company-wide (no property)')], default='every_property', help_text='What this rule applies to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Only used when Target type is "Specific property".', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_templates', to='core.property'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='property_types',
            field=models.JSONField(blank=True, default=list, help_text='Only used when Target type is "Property category" — Property.Type codes this applies to (e.g. ["str", "commercial"]). JSONField (not ArrayField) so this works on SQLite dev and Postgres prod alike.'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='required_attributes',
            field=models.ManyToManyField(blank=True, help_text='Property must have ALL of these tags for this template to auto-apply. Empty = no constraint. Layered on top of "Every property" or "Property category" targeting.', related_name='required_by_templates', to='core.propertyattribute'),
        ),
    ]
