# Generated by Django 6.0.7 on 2026-07-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_property_access_info_and_system_locations'),
        ('tickets', '0014_backfill_target_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followuplog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.property'),
        ),
        migrations.AlterField(
            model_name='followuplog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='tickets.ticket'),
        ),
        migrations.AddConstraint(
            model_name='followuplog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', True), ('ticket__isnull', False)), models.Q(('property__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='followuplog_exactly_one_of_ticket_or_property'),
        ),
    ]
