# Generated by Django 6.0.7 on 2026-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_followuplog_ticket_or_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status_reason',
            field=models.CharField(blank=True, help_text='Why this was Blocked / Skipped / Not applicable — see REASON_REQUIRED_STATUSES.', max_length=300),
        ),
    ]
