# Generated by Django 6.0.7 on 2026-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticketview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='delayed',
            field=models.BooleanField(default=False, help_text='True once due_date has been pushed later via the Edit Due Date action — a lesser flag than Overdue, meant to surface "we said we\'d push through this by X and didn\'t" separately from genuinely missed work.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='previous_due_date',
            field=models.DateTimeField(blank=True, help_text='The due_date immediately before the most recent push-back — shown translucent/struck-through next to the new date. Cleared (along with delayed) if due_date is ever moved back to or before this value.', null=True),
        ),
    ]
