# Generated by Django 6.0.7 on 2026-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_delayed_ticket_previous_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignmentlog',
            name='previous_conversation_id',
            field=models.CharField(blank=True, help_text="Set when a contractor change resets Ticket.source_reference — the old Quo conversation this ticket was bound to, so its history stays reachable (see ticket_detail.html's audit trail) instead of just disappearing.", max_length=100),
        ),
    ]
