# Generated by Django 6.0.7 on 2026-07-25 19:57

from django.db import migrations, models


def backfill_department(apps, schema_editor):
    """Every existing TaskPackage's steps already share one
    default_assigned_role in practice (that's how the app already treats a
    Function as belonging to one department) — this just makes it explicit
    on the package itself instead of leaving it implied. Left blank (an
    admin fills it in via /admin/) for the rare package whose steps
    disagree, rather than guessing which one is "right"."""
    TaskPackage = apps.get_model('tickets', 'TaskPackage')
    for package in TaskPackage.objects.prefetch_related('steps__template'):
        roles = {step.template.default_assigned_role for step in package.steps.all() if step.template_id}
        if len(roles) == 1:
            package.department = roles.pop()
            package.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticketassignmentlog_previous_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpackage',
            name='department',
            field=models.CharField(choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], default='', help_text='Which single department this Function belongs to — its steps normally all share one default_assigned_role already; this makes that explicit rather than implied.', max_length=20),
        ),
        migrations.RunPython(backfill_department, migrations.RunPython.noop),
    ]
