# Generated by Django 6.0.7 on 2026-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_taskpackage_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vendor_link_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time the vendor completion-form link was texted to the assigned contractor from the Contractor Communication card — rate-limits that button to once per 24h.', null=True),
        ),
    ]
