# Generated by Django 6.0.7 on 2026-07-26 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticketstatusnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='tickets.taskpackage')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='taskpackagetemplate',
            name='task_group',
            field=models.ForeignKey(blank=True, help_text='Optional — leave blank for a task that hangs directly off the Function rather than one of its Task Groups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tickets.taskgroup'),
        ),
    ]
