# Generated by Django 6.0.7 on 2026-07-26 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_taskgroup_taskpackagetemplate_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpackagetemplate',
            name='task_group',
            field=models.ForeignKey(blank=True, help_text='Optional — leave blank for a task that hangs directly off the Function rather than one of its Task Groups. Deleting the group ungroups its tasks rather than deleting them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='tickets.taskgroup'),
        ),
    ]
