# Generated by Django 6.0.7 on 2026-07-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_taskpackagetemplate_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='property_types',
            field=models.JSONField(blank=True, default=list, help_text="Broad property category this group's tasks apply to (e.g. Short-Term Rentals). Leave empty to have each task in this group use its own Target settings instead."),
        ),
    ]
