# Generated by Django 6.0.7 on 2026-07-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_taskgroup_property_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('upcoming', 'Upcoming'), ('vendor_complete', 'Vendor Complete'), ('completed', 'Completed'), ('verified', 'Verified'), ('skipped', 'Skipped'), ('not_applicable', 'Not applicable'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
