# Generated by Django 6.0.7 on 2026-07-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_tickettemplatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='duplicate_reasoning',
            field=models.TextField(blank=True, help_text="Claude's reasoning for flagging possible_duplicate_of."),
        ),
        migrations.AddField(
            model_name='ticket',
            name='possible_duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Set by intake/duplicate_classifier.py when a newly-created ticket looks like it describes the same real-world issue as an already-open ticket at the same property. Held in the Pending screen\'s "Possible duplicate" queue until a human confirms or dismisses the match — never auto-merged or auto-cancelled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='tickets.ticket'),
        ),
    ]
