# Generated by Django 6.0.7 on 2026-08-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_propertylistingname_and_more'),
        ('tickets', '0029_alter_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-assigned')], default='manual', help_text='Whether assigned_staff was picked by a human or filled in automatically from DepartmentDefaultAssignee at creation because assigned_role had one and nobody specific was chosen (see save()). Flipped back to "manual" the moment a human reassigns it — this only ever means "auto and still exactly as auto left it."', max_length=10),
        ),
        migrations.CreateModel(
            name='DepartmentDefaultAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('property_manager', 'Property Manager'), ('maintenance', 'Maintenance'), ('cleaner', 'Cleaner'), ('contractor', 'Contractor'), ('accounting', 'Accounting')], max_length=20, unique=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_for_roles', to='core.staffprofile')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
