# Generated by Django 6.0.7 on 2026-08-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_ticket_assignment_source_departmentdefaultassignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When status last changed — set automatically in save() (see from_db()). Powers "Xd blocked"/"Xd since" duration displays on the owner dashboard, since a status value alone (e.g. "blocked") has no inherent sense of how long it\'s been that way. Null means never changed since creation — fall back to created_at.', null=True),
        ),
    ]
