# Generated by Django 6.0.7 on 2026-08-04 23:08

from django.db import migrations, models


def backfill_assignment(apps, schema_editor):
    """Runs during `migrate` itself, BEFORE the AddConstraint operation
    right after it in this same migration — not a separate Procfile
    command whose completion has to be confirmed out-of-band first. Every
    ticket with neither assigned_staff nor assigned_contact gets a
    DepartmentDefaultAssignee match for its assigned_role, or any
    company-admin StaffProfile as a last resort, so the tightened
    constraint that follows can never fail on pre-existing data —
    regardless of whether tickets.backfill_ticket_assignment (the
    idempotent Procfile command doing the same thing) has run yet on this
    deploy or not."""
    Ticket = apps.get_model('tickets', 'Ticket')
    DepartmentDefaultAssignee = apps.get_model('tickets', 'DepartmentDefaultAssignee')
    StaffProfile = apps.get_model('core', 'StaffProfile')

    defaults_by_role = dict(DepartmentDefaultAssignee.objects.values_list('role', 'staff_id'))
    fallback = StaffProfile.objects.filter(is_company_admin=True).first()
    fallback_id = fallback.pk if fallback else None

    for ticket in Ticket.objects.filter(assigned_staff__isnull=True, assigned_contact__isnull=True):
        staff_id = defaults_by_role.get(ticket.assigned_role) or fallback_id
        if staff_id:
            ticket.assigned_staff_id = staff_id
            ticket.assignment_source = 'auto'
            ticket.save(update_fields=['assigned_staff', 'assignment_source'])
        # If neither a department default nor any company-admin exists at
        # all, this row is left as-is and the AddConstraint step below
        # will fail loudly — the correct outcome: better a failed deploy
        # that says exactly what's missing than a silent partial backfill.


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_propertylistingname_and_more'),
        ('tickets', '0031_ticket_status_changed_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_single_assignee',
        ),
        migrations.RunPython(backfill_assignment, noop_reverse),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_staff__isnull', False), ('assigned_contact__isnull', True)), models.Q(('assigned_staff__isnull', True), ('assigned_contact__isnull', False)), _connector='OR'), name='ticket_exactly_one_assignee'),
        ),
    ]
