# Generated by Django 6.0.7 on 2026-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_remove_ticket_ticket_single_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email'), ('quo', 'Phone (Quo)'), ('calendar', 'Calendar'), ('airbnb', 'Airbnb'), ('vrbo', 'VRBO'), ('fake', 'Simulated (dev)'), ('recurring', 'Recurring template'), ('onsite', 'On-site visit'), ('session', 'Recurring session')], default='manual', max_length=20),
        ),
    ]
