# Generated by Django 6.0.7 on 2026-08-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_propertylistingname_unit'),
        ('tickets', '0033_alter_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Which unit under the property this is about, if the property has units and it\'s known — e.g. "AC broken in 3B." Optional even on a multi-unit property: a building-wide issue is still just filed against the property with no unit set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.unit'),
        ),
    ]
