# Generated by Django 6.0.7 on 2026-08-20 12:53

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_ticketclosingnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='ticket_attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tickettemplatedocument',
            name='file',
            field=models.FileField(storage=core.storage.DocumentStorage(), upload_to='ticket_template_documents/%Y/%m/'),
        ),
    ]
