# Generated by Django 6.0.7 on 2026-08-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_alter_ticketattachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The staff user who was actually at the keyboard when this ticket was created, if any — set from the New Ticket form, a process-step task assignment, a promoted session line, or a staff-side visit status override that converted a reported issue. Orthogonal to `source` (which workflow produced the ticket): a fully automated origin (email/Quo/booking-triggered/recurring template/a cleaner\'s own token-link submit) has no human author at creation time, so this stays blank there — that absence IS the answer for "who created this," not a data gap to fill in later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
