# Generated by Django 6.0.8 on 2026-09-24 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0062_copy_recontie_to_reconmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, help_text='Groups the list, e.g. "Collections", "Sales and transfers".', max_length=60)),
                ('statute', models.CharField(blank=True, help_text='The statute the wording rests on, e.g. "§718.121(5), Florida Statutes".', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(help_text='The document, as HTML with {{ merge fields }}.')),
                ('fields', models.JSONField(default=list, help_text='Every input: key, label, type, prefill, default, required, help, remember.')),
                ('reviewed_note', models.TextField(blank=True, help_text='What still needs a lawyer or the board to confirm, or was last confirmed.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('companion_of', models.ForeignKey(blank=True, help_text='For a document that goes with another (an affidavit of mailing goes with a notice): the one it goes with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='legalforms.documenttemplate')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.PositiveIntegerField()),
                ('subject', models.CharField(blank=True, help_text='Who/what it is about, for the list: "Fernando Suzuki — Unit 32".', max_length=200)),
                ('values', models.JSONField(default=dict)),
                ('body_html', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('mailed_on', models.DateField(blank=True, null=True)),
                ('mail_method', models.CharField(blank=True, help_text='e.g. First class mail, Certified mail, Email.', max_length=60)),
                ('tracking', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='The document this one goes with (an affidavit -> its notice).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='legalforms.generateddocument')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_documents', to='core.property')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='legalforms.documenttemplate')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_documents', to='core.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', '-created_at'], name='legalforms__propert_8dbe44_idx')],
            },
        ),
    ]
